### ISSUE TITLE
Toggling inlay hints doesn't seem to work

### ISSUE THREAD

**Issue by MariaSolOs** [pmizio/typescript-tools.nvim#100]
I [toggle inlay hints](https://github.com/MariaSolOs/dotfiles/blob/ff2a6e9c27c617e4c11b6f2251aeed4d27ffc507/.config/nvim/lua/helpers/lsp.lua#L63) so that they are disabled when I'm in insert mode. This works as expected in Lua and Rust, but not in TypeScript. Instead, inlay hints always show up when I'm using this plugin.

**Comment by pmizio** [comment]
Interesting, you call nvim api to hide it and they still show up. I don't have any idea from top of my head but we look into it. @KostkaBrukowa can you also check out, you implemented inlay hints initially maybe you figure it out faster.

**Comment by MariaSolOs** [comment]
Never mind, I was just able to reproduce the issue in a non-TypeScript file, and so I think this a bug in Neovim.
