### ISSUE TITLE
Error after install: received end message with no corresponding begin

### ISSUE THREAD

**Issue by bmulholland** [pmizio/typescript-tools.nvim#101]
This is what I see after vim startup: "LSP[typescript-tools] received `end` message with no corresponding `begin`"

lazy.nvim with:
```lua
	{
		"pmizio/typescript-tools.nvim",
		dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
		opts = {},
	},
```

Initialized with:
```lua
require("typescript-tools").setup({
	on_attach = function(client)
		-- Leave the formatting to ESLint_d via null_ls
		client.server_capabilities.documentFormattingProvider = false -- 0.8 and later
	end,
})
```

**Comment by pmizio** [comment]
```lua
opts = {},
```

In lazy configuration call `require("typescript-tools").setup(...)` under the hood. Try to remove this line or move your `on_attach` fn into `opts` table then retest.

**Comment by bmulholland** [comment]
Thanks for the plugin, and for the help!

I tried removing opts and keeping the setup call. I also tried keeping opts and using the setup call. I tried the setup call with and without the on_attach (i.e. passing in a blank object). All of them resulted in the same error message on startup :(

**Comment by pmizio** [comment]
Ok, then I need more info about your setup:
- nvim version
- typescript version installed locally in your workspace
- typescript version installed globally (if it is installed)

**Comment by pmizio** [comment]
@bmulholland You may also set [this property](https://github.com/pmizio/typescript-tools.nvim/blob/fffd5ed6781fe3943216e2b57124f81e1c398647/lua/typescript-tools/config.lua#L52) as `"verbose"` to save tsserver logs, they live in `<tmp dir of your os>/tsserver_syntax.log` and `<tmp dir of your os>/tsserver_semantic.log`. They can be helpful in debugging also.

**Comment by bmulholland** [comment]
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

yarn.lock shows typescript 5.1.6. I don't _think_ it's installed globally, though I'm still learning asdf after a recent switch.

It looks like linting is running, and I tried adding missing imports and that worked, so I'm guessing most of the LSP is set up and working. I do get an error from nvim-lightbulb about a canceled LSP request; I'm not 100% that it's related.

i will try the logs...

**Comment by pmizio** [comment]
Ok, so If you provide logs it may help but, more or less I know what is going on.
nvim-lightbulb is for sure separate issue.

**Comment by bmulholland** [comment]
It was hard to track down the tmp dir; turns out on macOS that's a totally random series of directories. I found it with `echo $TMPDIR`

I don't see any immediate error in the logs, it seems to start up and provide responses just fine. Looks like the logs contain all my dependencies and much of my code; for security reasons I don't want to expose that to the public internet. Happy to send excerpts if it would help -- what should I look for?

**Comment by pmizio** [comment]
Ok, so problem is based on events tsserver emits while loading project. I think start event isn't emitted, but project loading end is. This error out nvim because we try to end unstarted thing.
First look for `projectLoadingStart` event if it isn't present look for  end `projectLoadingFinish` and try to move back in logs to nearest event which look like something which indicate start of loading. Maybe in your setup because of reasons start event isn't emitted or another event is emitted, I'm not sure.

**Comment by pmizio** [comment]
Can you install plugin from [this pr](https://github.com/pmizio/typescript-tools.nvim/pull/104) branch, it may help.
I just realized we run 2 servers and each one reports progress on same token, it can be race condition where one server stop loading before other and delete token. If this not help try to search logs like I wrote above.

**Comment by bmulholland** [comment]
That PR fixes it! Nice work


(Yes, there's a loading start)
```
Info 20   [13:41:45.932] event:
    {
     "seq": 0,
     "type": "event",
     "event": "projectLoadingStart",
     "body": {
      "projectName": "/Users/bmulholland/dev/recital/recital-frontend/tsconfig.json",
      "reason": "Creating possible configured project for /Users/bmulholland/dev/recital/recital-frontend/plugins/logUsage.ts to open"
     }
    }
```

**Comment by pmizio** [comment]
Then my idea was correct, nice. Ok, so I merge this, and closing.
