### ISSUE TITLE
Start LSP in Vue Single-File Components?

### ISSUE THREAD

**Issue by bmulholland** [pmizio/typescript-tools.nvim#102]
I use `.vue` files with Typescript in them. `typescript-tools` doesn't start for those files, as "vue" is not a listed filetype. Is there a configuration I need to set for that?

**Comment by pmizio** [comment]
Vue has its own language server(volar) which support typescript and it should be used in nvim for vue SFC's.
This is out of scope of this plugin.

**Comment by bmulholland** [comment]
Alas, Vue 3 only. Can't wait until we can upgrade...

**Comment by pmizio** [comment]
I think vuels(vetur) is for vue 2 for neovim it is included in nvim-lspconfig https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/vuels.lua you can try this.

**Comment by 9mm** [comment]
I have a side question... Ive heard vue/volar takeover mode is most efficient. How do I ensure everything is still efficient when working with non-view typescript files?

I have this currently in LSP config

```
        volar = {
          filetypes = { 'vue' }, -- skip takeover mode for now in favor of typescript-tools simultaneous server - https://github.com/johnsoncodehk/volar/discussions/471
        },
```

And then can I just leave `typescript-tools` as the default setup()?
