### ISSUE TITLE
Feature request: Allow tsserver installation via mason.nvim

### ISSUE THREAD

**Issue by TroySigX** [pmizio/typescript-tools.nvim#106]

**Comment by KostkaBrukowa** [comment]
Is this even possible? In the docs of `mason.nvim` it states that `Neovim plugin that allows you to easily manage **external** editor tooling`. `typescript-tools` is not external tool - it is internal plugin. I'm wondering if there is some other nvim plugin (like `rust-tools`) that is available through mason?

**Comment by pmizio** [comment]
Not exactly but we can make mason integration layer similar to https://github.com/jay-babu/mason-null-ls.nvim which for example help to install all supported tsserver versions and plugins. And default to mason when local and global installation isn't present.

**Comment by TroySigX** [comment]
I'm confused. Did you mean installing `tsserver` or `typescript-tools` via mason?

**Comment by pmizio** [comment]
I mean tsserver and tsserver plugins(styled components for eg) to be installed via mason. typescript-tools need to be installed separately using nvim package manager.

**Comment by TroySigX** [comment]
Yeah, conventionally, I'd install `tsserver` through `mason`, but after switching to `typescript-tools` (which is already installed using nvim package manager), it doesn't seem to work.

**Comment by TroySigX** [comment]
I figured it out, here's my config:
```lua
local mason_registry = require('mason-registry')
local tsserver_path = require('mason-registry').get_package('typescript-language-server'):get_install_path()
require("typescript-tools").setup({
settings = {
  tsserver_path = tsserver_path .. '/node_modules/typescript/lib/tsserver.js',
}
})
```
