### ISSUE TITLE
Error executing vim.schedule lua callback: ... attempt to index local 'request' (a nil value) 

### ISSUE THREAD

**Issue by bmalinconico** [pmizio/typescript-tools.nvim#111]
I've started getting the same (similar) error to #54 

```
Error executing vim.schedule lua callback: ...r/neovim/HEAD-63b3408/share/nvim/runtime/lua/vim/lsp.lua:1500: attempt to index local 'request' (a nil value)                                                                                                                                  
stack traceback:
        ...r/neovim/HEAD-63b3408/share/nvim/runtime/lua/vim/lsp.lua:1500: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323
```

Neovim version:

```
NVIM v0.10.0-dev-4718+g63b340855-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

typescript-tools.nvim version `a835f0c`

Lazy config:

```
require("lazy").setup({
  {
    "pmizio/typescript-tools.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    opts = {},
  }
})
```

This is the only plugin installed except what is required for support.

I've been debugging and it appears `TSToolsAddMissingImports` throws this error when it makes no changes.

So to be clear, this error shows up when I save a file before the tsserver is running, or when there are no changes made.

Please let me know whatI can do to help debug the issue.

**Comment by pmizio** [comment]
Yes, I recently fixed one error and created other one :D I posted pr with fix can you take a look and confirm branch from this pr fixes issue?

**Comment by bmalinconico** [comment]
Looks like i'm now getting:

```
Error executing vim.schedule lua callback: ...vim/HEAD-63b3408/share/nvim/runtime/lua/vim/lsp/util.lua:889: attempt to index local 'workspace_edit' (a nil value)                                                                                                                             
stack traceback: 
```

**Comment by bmalinconico** [comment]
I take it back, when I have no other plugins installed i'm not getting that error. I'll try and bisect which once is causing issues with this one later.

**Comment by pmizio** [comment]
Ok, I suppose it fails on [this](https://github.com/pmizio/typescript-tools.nvim/blob/a996a00b8f7e5411cf2ca7e0da8c64094ea18b1b/lua/typescript-tools/api.lua#L34) line, but I'm not sure because you cut  stacktrace from error maybe it has location in plugin code, but I pushed blindly something which may help. If it does not help I need to wait for your investigation regarding plugins.

**Comment by pmizio** [comment]
Just, merged pr for other users but ofc we can continue to debug this.

**Comment by bmalinconico** [comment]
alright i've played around with it again (using master) and I can't re-create the issue. Thanks for your help and the fast response.
