### ISSUE TITLE
no syntax highlighting for textDocument/hover by lspsaga.nvim

### ISSUE THREAD

**Issue by sternelee** [pmizio/typescript-tools.nvim#118]
This is a comparison with typescript.nvim

<img width="1545" alt="iShot_2023-07-26_10 05 19" src="https://github.com/pmizio/typescript-tools.nvim/assets/6971752/945e6d37-3527-4ae9-9432-51d5ec475296">
<img width="1541" alt="iShot_2023-07-26_10 06 00" src="https://github.com/pmizio/typescript-tools.nvim/assets/6971752/ece08d22-b126-4504-9fa2-6d7c666c792a">

**Comment by pmizio** [comment]
Yup this is a bug, but it can be fixed easly, I do this later today.

**Comment by pmizio** [comment]
@sternelee It should be fixed on branch from [this](https://github.com/pmizio/typescript-tools.nvim/pull/120) pr, can you confirm this?

**Comment by sternelee** [comment]
@pmizio good, it work, ths

**Comment by pmizio** [comment]
@sternelee it's now on master thanks for report!
