### ISSUE TITLE
Lsp signature has multiple sources

### ISSUE THREAD

**Issue by edward-s** [pmizio/typescript-tools.nvim#122]
Not sure if I describe it correctly, so I attached a screenshot.

I'm seeing double information when i view lsp signature, i only want one

<img width="359" alt="Screenshot 2023-07-31 at 5 16 50 PM" src="https://github.com/pmizio/typescript-tools.nvim/assets/237278/874848ce-7a00-4fb8-99b6-470e558755a2">

**Comment by pmizio** [comment]
@edward-s You didn't disable `typescript-language-server`(from mason/nvim-lspconfig) so you get two responses from two separate servers and lspsaga show you both. This plugin is drop in replacement for `typescript-language-server` so you can just remove it then you will get only one message. With red I marked sources from where you get responses:
<img width="556" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/4346598/7db0332f-4a95-4449-a3ed-5a465b578558">
