### ISSUE TITLE
Plugin can't find tsserver

### ISSUE THREAD

**Issue by rwxmad** [pmizio/typescript-tools.nvim#129]
I have tsserver installed using [mason](https://github.com/williamboman/mason.nvim), but when I open the ts file I get an error:
```
Error executing luv callback:
...pt-tools.nvim/lua/typescript-tools/tsserver_provider.lua:133: Cannot find tsserver executable in local project nor global npm installation.
stack traceback:
	[builtin#36]: at 0x0104ce461c
Error executing luv callback:
...pt-tools.nvim/lua/typescript-tools/tsserver_provider.lua:133: Cannot find tsserver executable in local project nor global npm installation.
stack traceback:
	[builtin#36]: at 0x0104ce461c
Error executing luv callback:
cannot resume dead coroutine
```

I tried to specify the path to the executable file, but the error persists
```
    require('typescript-tools').setup({
      on_attach = on_attach,
      settings = {
        tsserver_path = '~/.local/share/nvim/mason/bin/typescript-language-server',
        separate_diagnostic_server = true,
        tsserver_file_preferences = {
          includeInlayParameterNameHints = 'all',
          includeCompletionsForModuleExports = true,
          quotePreference = 'auto',
        },
      },
    })

```

**Comment by pmizio** [comment]
It is common misconception, thing you installing using mason isn't tsserver. It is just wrongly named in mason, but package you install depends on tsserver so you still can reuse this. Take look for snippet [here](https://github.com/pmizio/typescript-tools.nvim/issues/106#issuecomment-1637124589). It should work. Let me know.

**Comment by rwxmad** [comment]
@pmizio if i use snippet from [here](https://github.com/pmizio/typescript-tools.nvim/issues/106#issuecomment-1637124589) - everything works fine, thanks a lot

**Comment by pmizio** [comment]
Nice closing then
