### ISSUE TITLE
Conflict with tree-sitter ? 

### ISSUE THREAD

**Issue by filipslezaklab** [pmizio/typescript-tools.nvim#131]
Did not know how to title this, sorry.

Whenever this plugin is loaded after opening .ts or .tsx file everything turns red for me. It's like tree-sitter was not present or tsx for it was not installed. When I turn this plugin off, everything is looking as it should. For first when the file is opened it looks normal but when ts-tools finishes loading all except JSX tags turns red.

I am using lazy.nvim and my base config is NvChad.

I don't know what can be useful for diagnostics, so I will provide everything I can if requested.

I love the work that is being done here, especially custom user commands are super useful <3.

**Comment by pmizio** [comment]
Probably not, we don't use treesitter in this plugin at all. It may be conflict with some other plugin or even something wrong in your configuration. If you provide me more context, minimal or easily reproducible config, then I'll try to help.

**Comment by filipslezaklab** [comment]
Finally, I had some time to swap back to typescript-tools for testing and after updating everything, the problem did not appear so I assume it had something to do with the versions of plugins I had at the time. If it reappears I will open a new issue and publish my whole config in some GitHub repo.
