### ISSUE TITLE
Customize underlying tsserver `setup()`

### ISSUE THREAD

**Issue by nekowinston** [pmizio/typescript-tools.nvim#132]
Hey there, thanks for your work on this plugin.

I would like to turn off `single_file_support` (or change `root_dir`), since it causes many conflicts when working with Deno, how am I supposed to do that?
https://github.com/pmizio/typescript-tools.nvim/blob/3b05146d96b7c3d86e5f540d9ac871823e318d5a/lua/typescript-tools/init.lua#L15-L44

**Comment by pmizio** [comment]
You can just put them into plugin setup function all code you pointed is only default configuration.

```lua
require("typescript-tools").setup {
  -- here put lspconfig props
  settings = {
    -- here is place of any option introduced by this plugin
  }
}

**Comment by nekowinston** [comment]
Thank you!
I completely missed the first part of the README/Configuring, I noticed that `on_attach` was shown in the example, but didn't make the connection that the rest would work.
