### ISSUE TITLE
[Feature request] lsp method textDocument/declaration

### ISSUE THREAD

**Issue by TroySigX** [pmizio/typescript-tools.nvim#133]
I feel that in large projects, trying to import some file using its relative path can be very time-consuming. So the textDocument/declaration method, which automatically finds the relative path for completion, should be top-priority? It can save a huge amount of time.

**Comment by pmizio** [comment]
Sorry I don't get what you mean, I suppose you manually "dotting" to get to the some file to import it?

If yes you have few other ways to automatically bring import:

1. While you're typing name of whatever you want to import you should get autocompletion if you select it and confirm it(<C-y> in nvim-cmp) then autoimport should kick in.
2. You type entire thing and execute `vim.lsp.buf.code_action()` then one of it also should be "Import XYZ from x/y/z"

About declaration request I don't think it work like you think, it operate on known(previously imported) sympol under cursor, and as far as I know it isn't supported in underlying tsserver.

But maybe I don't understand what you mean exactly and please elaborate more on it.

**Comment by TroySigX** [comment]
Oh yeah, you're write. My bad, sorry. Mine didn't work because `typescript-tools` doesn't initialize in my project. But after removing and cloning my project again, it works again. Thank you!

**Comment by TroySigX** [comment]
Oh, I see what's going wrong here, I've created a new issue and am gonna just leave the [link](#134) here.
