### ISSUE TITLE
[Bug] Cannot autoimport function as const

### ISSUE THREAD

**Issue by TroySigX** [pmizio/typescript-tools.nvim#134]
I have a javascript file with the following content:
```javascript
export const tryFunc = (a, b) => {
  return a + b;
};
```

Trying to import `tryFunc` from another file (and autocomplete with its relative file path) just doesn't work.

**Comment by pmizio** [comment]
@TroySigX I can confirm, but it isn't plugin problem, its setup of your project. To make it work you need to set `"allowJs": true` in your `tsconfig.json` or if you in pure js project you need `jsconfig.json` file to tsserver properly index project and provide proper completions.

**Comment by TroySigX** [comment]
hmm, I don't know, but the typescript-language-server works even when I don't set allowJs.
