### ISSUE TITLE
Bug: unable to find global tsserver executable installed by Volta

### ISSUE THREAD

**Issue by benelan** [pmizio/typescript-tools.nvim#135]
## Description

I use [volta](https://docs.volta.sh/guide/understanding) to manage my npm/node installations. This is how Volta describes how it works in [their doc](https://docs.volta.sh/guide/#how-does-it-work):

> Volta does not use any fancy OS features or shell-specific hooks. It’s built on the simple, proven approach of shims.
>
> Whenever you install a tool with Volta, it adds a shim to your PATH that acts as an intelligent (and fast) router to the right version of the tool and runs it with the right Node engine.

I get the following error when opening a typescript file that is not in a project with it's own typescript installation:

```log
Error executing luv callback:
...pt-tools.nvim/lua/typescript-tools/tsserver_provider.lua:133: Cannot find tsserver executable in local project nor global npm installation.
stack traceback:
        [builtin#36]: at 0x559ada891be0
```

Unfortunately setting the `tsserver_path` option doesn't help. Here is a minimal repro sample:

```lua
-- test.lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup(
{
  "pmizio/typescript-tools.nvim",
  dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  opts = {
    tsserver_path = vim.env.HOME .. 
        "/.volta/tools/image/packages/typescript/lib/node_modules/typescript/lib/tsserver.js"
    },
})

```

I get the error when opening neovim like this:

```sh
neovim -u test.lua foo.ts
```
I didn't see any info about debug logs, but I can provide them if they exist, just let me know.

Here is some potentially helpful info about my machine:
```sh
neofetch # -> OS: Pop!_OS 22.04 LTS x86_64
         # -> Shell: bash 5.1.16
volta -v # -> 1.1.1
node -v  # -> 16.20.1
npm -v   # -> 8.19.4
```
I ran `npm install -g typescript@latest` to make sure I'm on a supported version and it still repros.

Let me know if there is anything else I can provide. Thanks!

**Comment by pmizio** [comment]
It should be like below, because top level config object is passed to underlayig nvim-lspconfig `setup` function. All plugin specific options go into `settings` object:
```lua
{
  "pmizio/typescript-tools.nvim",
  dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  opts = {
    settings = {
      tsserver_path = vim.env.HOME .. 
        "/.volta/tools/image/packages/typescript/lib/node_modules/typescript/lib/tsserver.js"
     }
    }
```
