### ISSUE TITLE
Unwanted behavior from TSToolsAddMissingImports

### ISSUE THREAD

**Issue by milkias17** [pmizio/typescript-tools.nvim#137]
right now when you try to add missing imports, if there are namespace clashes meaning the same name can be found from multiple modules, it imports them all. I would think this would never be intended behavior, the sorting of which is better is more complicated but at least choosing one is I would think the better way to do it. [typescript.nvim](https://github.com/jose-elias-alvarez/typescript.nvim) did handle this correctly.

**Comment by pmizio** [comment]
Can you provide some code snippet which always trigger unwanted behavior, it will simplify resolving this issue, thanks!

**Comment by milkias17** [comment]
Since there would be a need for a namespace conflict, I don't know if I can provide one without installing external packages or something of that nature. In any case to make the case clear, I've attached a video depicting what happens
![depction](https://github.com/pmizio/typescript-tools.nvim/assets/66522725/f41b0239-5fa9-449b-aa6c-e73a0a2a2020)

**Comment by pmizio** [comment]
@milkias17 can you check linked pr?

**Comment by milkias17** [comment]
Yeah the linked PR does fix the issue. Thanks🙏

**Comment by pmizio** [comment]
Its on master now, thanks for report!
