### ISSUE TITLE
check current buffer and attach if filetype is suitable

### ISSUE THREAD

**Issue by JosefLitos** [pmizio/typescript-tools.nvim#141]
After going for nvim 0.10 nighly, lazy.nvim `ft` launching consumes the filetype event, meaning when I have a config like so:
```lua
return {
	'pmizio/typescript-tools.nvim',
	ft = { 'typescript', 'javascript', 'typescriptreact', 'javascriptreact' },
	dependencies = { 'nvim-lua/plenary.nvim', 'nvim-lspconfig' },
	config = true
}
```

typescript-tools won't launch on the first file opened.

It should check if the current file should have a client attached to it instead of only relying on filetype events.

**Comment by pmizio** [comment]
@JosefLitos I realized we have this problem before but it isn't our problem but underlying `nvim-lspconfig` one. The solution was posted here:
https://github.com/pmizio/typescript-tools.nvim/issues/55#issuecomment-1602751675

Let me know it fixes problem.

**Comment by JosefLitos** [comment]
Yes, of course that would, but I don't want to load the plugin when opening any file - that's the entire purpose of lazy loading. The `ft` hook is useless in that case.

**Comment by JosefLitos** [comment]
I didn't know this plugin uses `nvim-lspconfig` in this case the solution is so simple I think it may deserve to be mentioned in the docs:
```lua
{
	'pmizio/typescript-tools.nvim',
	ft = { 'typescript', 'javascript', 'typescriptreact', 'javascriptreact' },
	dependencies = { 'nvim-lua/plenary.nvim', 'nvim-lspconfig' },
	config = function()
		require('typescript-tools').setup {}
		require('lspconfig')["typescript-tools"].launch()
	end,
}
```
