### ISSUE TITLE
Better default formatting

### ISSUE THREAD

**Issue by Cretezy** [pmizio/typescript-tools.nvim#143]
It would be great if this integrated with common formatters (Prettier/ESLint) when they are present.

Alternatively, it would be nice to have editorconfig support.

**Comment by pmizio** [comment]
What do you mean by this integration? 
You want to load settings from this tools eg. how much spaces is tab etc.
Or you want to call them instead default tsserver formatting?

**Comment by Cretezy** [comment]
Ideally it would call Prettier (or `prettierd`) when formatting, but it would also be good if it automatically matched it.

Currently, I have to disable the formatting options from typescript-tools to properly format code in our project.

**Comment by pmizio** [comment]
So, this feature is out of scope of this plugin. We aim to support only features exposed by tsserver. So your solution is perfectly fine.
