### ISSUE TITLE
"remove unused imports" removes unused variables and function parameters

### ISSUE THREAD

**Issue by Hajime-Suzuki** [pmizio/typescript-tools.nvim#145]
When "remove unused imports" is executed, it removes not only unused imports but variables and params partially.

https://github.com/pmizio/typescript-tools.nvim/assets/26042720/fea94f98-ed26-4b8c-a03f-9219b3990e8f

Before:
```
import { isDefined } from './utils'

const test = (a: string) => null
const unused = () => null

test('a')
```

After:
```
const test = (g) => null

test('a')
```

Expected (what I get from VSCode):
```
const test = (a: string) => null
const unused = () => null

test('a')
```

My config (copy & paste from the readme + modified `expose_as_code_action`):
```lua
	require("typescript-tools").setup({
		on_attach = function(client, bufnr)
			require("user.plugins.lsp.mason.handlers").on_attach(client, bufnr)
		end,
		handlers = {},
		settings = {
			separate_diagnostic_server = true,
			publish_diagnostic_on = "insert_leave",
			expose_as_code_action = { "fix_all", "add_missing_imports", "remove_unused" },
			tsserver_path = nil,
			tsserver_plugins = {},
			tsserver_max_memory = "auto",
			tsserver_format_options = {},
			tsserver_file_preferences = {},
		},
	})
```

**Comment by KostkaBrukowa** [comment]
Good catch. In fact there was `TSToolsRemoveUnused` instead of `TSToolsRemoveUnusedImports` command run under the hood. Linked PR should fix this. You can take a look

**Comment by Hajime-Suzuki** [comment]
Thank you. Now it works as expected. Also, with the "all" option I see all code actions.

**Comment by pencilcheck** [comment]
I use organize imports and it just remove only unused imports

**Comment by samyarkd** [comment]
> I use organize imports and it just remove only unused imports

is this a prettier plugin ?
