### ISSUE TITLE
formatting handler only works in async mode

### ISSUE THREAD

**Issue by ribru17** [pmizio/typescript-tools.nvim#148]
Hi, I am trying to register a handler to `textDocument/formatting` that will call `api.sort_imports` each time. However I have noticed this handler is only executed when using async formatting (which I don't use), i.e. `vim.lsp.buf.format {async = true}`.

**Comment by pmizio** [comment]
Hi @ribru17 sorry for delay, I had a lot of my day job work.
It isn't related with plugin, this is a nvim code, sync format just apply edits and ignore handler:
https://github.com/neovim/neovim/blob/4607807f9fcb83d4e183f6f67e705ffd7f451077/runtime/lua/vim/lsp/buf.lua#L248

You should issue this in nvim core.

**Comment by ribru17** [comment]
I see, thank you for answering.
