### ISSUE TITLE
"Tsserver not found" , why not search PATH ?

### ISSUE THREAD

**Issue by LamprosPitsillos** [pmizio/typescript-tools.nvim#149]
https://github.com/pmizio/typescript-tools.nvim/blob/1b0af278f7415bc8fbb8128af99622dffcf5a9c2/lua/typescript-tools/tsserver_provider.lua#L106

I have installed `typescript` on my NixOs system ,allong with the `tsserver` .
But i still get error that 
```
/tsserver_provider.lua:133: Cannot find tsserver executable in local project nor global n
pm installation.                                                    
```

Since i have it installed , i took a look at the source code and saw that no check is done on the PATH.
I was wondering , is there a reason for this ? Does the tsserver has to be in the root of the project ? I imagine not, because `node -g ` is also supported .

If no reason exists , and if you are ok with it , would a PR be accepted ?
Thanks

**Comment by pmizio** [comment]
Hi @LamprosPitsillos I fixed it here: https://github.com/pmizio/typescript-tools.nvim/pull/152
can you take a look it is working for you?
