### ISSUE TITLE
tstools stopped working without obvious reason

### ISSUE THREAD

**Issue by JosefLitos** [pmizio/typescript-tools.nvim#151]
4 or 3 weeks ago everything was working just fine. I tried older commits of this plugin, typescript itself, lspconfig, neovim/nightly, but without any success. This hasn't been happening to me with any other lsp.

The issue stays the same: I open a `.ts` file and eslint loads fine, but `typescript-tools` does not. When I look into
```lua
require'lspconfig'['typescript-tools'].manager
```
it (`._clients`) shows the correct root directory with an existing client. But it is never attached, not even when trying to reopen the file or any other from the project. The instance also doesn't show any attached buffers (`:clients()[1]`). Trying to attach it through calling `:clients()[1]._on_attach(vim.fn.bufnr())` did change the `attached_buffers` of the clients table but didn't actually attach the client.

This is not really helpful information, but I ran out of ideas to try.

**Comment by pmizio** [comment]
You tried to start it with simple `:LspStart typescript-tools`?
I don't have idea why this is happening, I'm on latest nightly and latest plugin commit everything working for me.
Can you provide minimal reproduction config?

**Comment by JosefLitos** [comment]
`:LspStart typescript-tools` does nothing, `LspRestart` causes error:
`tsserver.lua:303: attempt to index field 'process' (a nil value)` called from `lsp.lua:1933 function 'stop', tstools/rpc.lua:41`

Since I cannot get the lsp to work it is hard to ensure the minimal config is correct, but I assume this should work:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd('set packpath=/tmp/nvim/site')

local package_root = '/tmp/nvim/site/pack/test/start/'
local lspconfig_path = package_root .. 'nvim-lspconfig'

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
  vim.fn.system { 'git', 'clone', 'https://github.com/pmizio/typescript-tools.nvim', package_root..'typescript-tools.nvim' }
  vim.fn.system { 'git', 'clone', 'https://github.com/nvim-lua/plenary.nvim', package_root..'plenary.nvim' }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)

require'typescript-tools'.setup{
	on_attach = function(client, bufnr)
		vim.api.nvim_echo({{vim.inspect({client=client,buf=bufnr})}},false,{})
	end,
	settings = {
		tsserver_path = '/usr/bin/tsserver'
	}
}
```

open a `.ts` file and run `:LspStart typescript-tools`

**Comment by JosefLitos** [comment]
Yeah, for me it works on an older system too. I will try to update package by package and see.

**Comment by JosefLitos** [comment]
I found the issue - tstools is calling `npm root -g`, this is what my main system responds with:
```
/usr/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/classes/range.js:188:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/functions/satisfies.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.6.1
```
whereas my other system responds normally: `/usr/lib/node_modules`

**Comment by JosefLitos** [comment]
Fixed as mentioned in the related npm issue / archlinux package: `sudo rm -rf /usr/lib/node_modules/npm/`

Issue likely caused by: upgrading from an old package stored under `npm/node_modules` instead of being a system package like `npm`. The same happens when `semver` is installed through `npm -i -g semver`.

**Comment by dcousens** [comment]
If you don't have `npm`
```
#!/bin/bash
echo /usr/lib/node_modules
```

**Comment by dcousens** [comment]
Can we update the title of this issue to `attempt to index field 'process' (a nil value)` for SEO? 💛
