### ISSUE TITLE
Inlay hints remain after removing code

### ISSUE THREAD

**Issue by MariaSolOs** [pmizio/typescript-tools.nvim#156]
After removing a line with inlay hints the code is removed but the hints remain:

https://github.com/pmizio/typescript-tools.nvim/assets/62502207/73a29141-91e8-4fae-944e-3aa375cc15aa

I don't believe this is an editor issue since I haven't been able to reproduce it with other language servers...

**Comment by pmizio** [comment]
To the start of next week I'm out of office, I'll check this when I get back from vacation.

**Comment by MariaSolOs** [comment]
@pmizio sounds good! If it helps, while debugging this I'm seeing that my `on_attach` function isn't being called...

**Comment by pmizio** [comment]
Once again thanks for fixing this issue!
