### ISSUE TITLE
bug: "remove unused declaration" only removes the function body

### ISSUE THREAD

**Issue by llllvvuu** [pmizio/typescript-tools.nvim#157]
Suppose you have unused declaration like this:

```typescript
const foo = () => {
  console.log("bar")
}

function foo() {
  console.log("bar")
}
```

Code actions while hovered over "foo" works okay. But code action while hovered over "{" shows "Remove unused declaration for '{'" and it removes only the function body. I don't know if this is an issue from upstream.

**Comment by pmizio** [comment]
To the start of next week I'm out of office, I'll check this when I get back from vacation.

**Comment by KostkaBrukowa** [comment]
I can see that in TLS it works exactly the same, and in VSCode there is no code action at all when you hover the `{`. Personally I don't think it's an issue, because `Remove unused declaration for '{'` works correctly (it removes the braces) so I would leave it as it is
