### ISSUE TITLE
vim.lsp.buf.rename() prompts and renames twice

### ISSUE THREAD

**Issue by synic** [pmizio/typescript-tools.nvim#158]
I've installed typescript-tools, uninstalled tsserver. When I go into a typescript document and type `:LspInfo`, I can see that both tsserver and typescript-tools are active, even though Mason shows that tsserver is not installed (maybe it comes with typescript tools?)

When I initiate a rename, it prompts twice, and renames twice. Maybe because there's two servers that called `on_attach` twice?

**Comment by pmizio** [comment]
If both servers are attached then it's issue in your config.
But, 1-st mason is only installer for lsp servers so besides of this you need to remove lspconfig setup for tsserver eg.
```
lspconfig['tsserver'].setup(...)
```

Need to be removed.

**Comment by KostkaBrukowa** [comment]
Do you have https://github.com/jose-elias-alvarez/typescript.nvim installed?

**Comment by synic** [comment]
@KostkaBrukowa yup, that was it. I was mostly using it for the `:TypescriptRenameFile`, but I can give that up ;-). Thank you!

**Comment by KostkaBrukowa** [comment]
@synic if you are using nvim-tree or neotree for renaming files you can look up https://github.com/antosha417/nvim-lsp-file-operations plugin. It works really well with typescript tools.

**Comment by synic** [comment]
@KostkaBrukowa ooh, I don't but maybe it's time to start. Thanks again!
