### ISSUE TITLE
Miss item for autoComplete

### ISSUE THREAD

**Issue by BingCoke** [pmizio/typescript-tools.nvim#159]
I'm not sure it is a bug for this plugin or not.
I use nvim-cmp for auto-completion,it may be the reason.

1. npm i -g @nestjs/cli && nest new app to build project
2. delete these lines in app.service.ts
```
import { Injectable } from '@nestjs/common';

@Injectable()
```
3. input "@inj" to auto import Injectable.But get nothing.
![image](https://github.com/pmizio/typescript-tools.nvim/assets/81607010/12e45921-6c24-466d-9736-fbbbd67414c0)
4. fire < a - space > will get juggestion list has injectable complete item.
![image](https://github.com/pmizio/typescript-tools.nvim/assets/81607010/cfffe9e5-f09f-4ba7-b059-621b56e982c7)

I initially thought it is a bug from cmp, but I find this issue. Finally them thought it is a error from lsp.
https://github.com/hrsh7th/nvim-cmp/issues/1176#issue-1368609448

but it can work fine in vscode.
![image](https://github.com/pmizio/typescript-tools.nvim/assets/81607010/fb8302c0-4c42-44f9-8ddc-776456d9c2d4)

As I said at the beginning, I don’t know which plug has the problem, but it is definitely not a problem with lsp. It can only be a problem with cmp or this plugin. I have open an issue with cmp, but no one has responded yet. I open an issue here to find out which plugin is the problem and get someone who has some problem.

**Comment by pmizio** [comment]
It may be connected to the fact that (this)[https://github.com/pmizio/typescript-tools.nvim/blob/5e6d0d6e8a5c9591bec34ca26c17e5b4ea98b460/lua/typescript-tools/capabilities.lua#L24] capability doesn't include `@` sign you may checkout repo and add it to test this hypothesis.

Saldly I'm out of office to the next week so I cannot test it for you. If this fix your issue pr is appreciated.

**Comment by BingCoke** [comment]
I dont konw rationale.but i Comment this line It turly fix this issue.Thanks.
![image](https://github.com/pmizio/typescript-tools.nvim/assets/81607010/6ba23fb3-05e3-43a2-a319-9453b8e0584c)

**Comment by BingCoke** [comment]
something interesting, I will get all item above of '@Injectable' but miss item above of class AppService

`above of appservice`
![image](https://github.com/hrsh7th/nvim-cmp/assets/81607010/07dd3560-6324-4699-8419-eeda9c6bd76b)

`above of 'Injectable'`
![image](https://github.com/hrsh7th/nvim-cmp/assets/81607010/56cb4fad-fa3d-47d5-b410-c797a638ea71)

**Comment by pmizio** [comment]
@BingCoke Ok so I looked into it and problem is out of this plugin - we get request for completion only once after `@` char then every next typed char don't trigger lsp request. Completion requests are sent by nvim-cmp so we need to search there.
I also checked it on `typescript-language-server` and problem also exists there, so I'm pretty confident it is something in nvim-cmp.
