### ISSUE TITLE
code action rename - doesn't work when it contains '$' (dollar sign)

### ISSUE THREAD

**Issue by IzioDev** [pmizio/typescript-tools.nvim#162]
Hi,

I'm not sure this is entirely related to this project, please let me know if not, and feel free to close this issue.

When I have a variable containing `$` (dollar sign), I can't rename:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/9900846/a40c5314-10e6-4359-affe-edf18fcdea9e)

Is it possible to let `angular-ls` manage this renaming otherwise?

Thanks in advance

**Comment by pmizio** [comment]
Hi, I'll have time to look into this in Monday. I'm not expert in angular stuff but I'm pretty sure angular-ls support also typescript similar trick is done in vue language servers.

You can test this by temporarly disabling typescript-tools.

Then reexecute rename and do other lsp related stuff.

If everything works correctly then you need to probably check if your project has some angular specific file or angular entry in `package.json` then if out setup function of my plugin to avoid spawning tsserver in angular project.

Let me know of result.

**Comment by pmizio** [comment]
@IzioDev do you have any special plugin for doing renames or something like this? I cannot reproduce this. For me `$` ended variables renameing just fine. One other thing can you provide some minimal project with this problem?

If you want to disable rename in `typescript-tools` in angular projects you can add below snippet to `on_attach` function passed to `require("typescript-tool").setup()`:
```lua
    local is_in_angular_project = #vim.tbl_filter(function(dir)
      return vim.fn.filereadable(vim.uri_to_fname(dir.uri) .. "/angular.json")
    end, client.workspace_folders) > 0

    if is_in_angular_project then
      client.server_capabilities.renameProvider = false
    end
```

**Comment by IzioDev** [comment]
maybe the renaming issue is occurring on `angular-ls` (cannot say for sure, can I?)

thanks for your time, i think we can safely close this issue :+1:
