### ISSUE TITLE
File table overflow error when running on Mac

### ISSUE THREAD

**Issue by noahbald** [pmizio/typescript-tools.nvim#166]
I'm running a particularly large project on my laptops and shortly after typescript-tools starts it causing other applications (such as Chrome) to crash due to too many files being open on the system.
Disabling this plugin seems to fix the issue.

Is there an option to limit files opened by the TypeScript LSP?

**Comment by pmizio** [comment]
I don't know about any setting in tsserver which limit files but you can try [this](https://github.com/pmizio/typescript-tools.nvim/blob/f7c45763fe1513e257ebf45bedfc5e6dd1aade78/README.md?plain=1#L140) option. It limit max memory used by tsserver maybe with this limit tsserver will be more aggressive with closing files.
When we enable similar option in VSC it's value is set to `4096`, so this is probably good starting point.
Second thing you can do is setting [this](https://github.com/pmizio/typescript-tools.nvim/blob/f7c45763fe1513e257ebf45bedfc5e6dd1aade78/README.md?plain=1#L124) option to `false` - this one disable second instance of tsserver which we spawn for performance reasons, but in your case it double memory and file descriptor usage.

If both of them fails then this is question for typescript devs, this plugin don't open any files by itself.

**Comment by noahbald** [comment]
Thanks @pmizio for the advice, unfortunately the issue still seems to occur even after setting those options to the values you suggested
