### ISSUE TITLE
Are there plans to support `JsxCloseTag`?

### ISSUE THREAD

**Issue by PHSix** [pmizio/typescript-tools.nvim#169]
I found that the native tsserver includes this command, and it's implemented in the `vscode extension` and `coc-tsserver`. However, it's not implemented in typescript-language-server because it doesn't meet the LSP standards. Are there any plans to implement this?

**Comment by KostkaBrukowa** [comment]
Just out of curiosity: why not use tsserver completion? If you type `</` then tsserver gives us completion of the jsx tag (like in the image below)

<img width="629" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/35625949/02c93814-d099-479c-af11-44a3eb3ce699">

**Comment by PHSix** [comment]
> We also doesn't want to go too far out of spec. There is some specific to this feature other than closing tag? If not nvim community has awesome [plugin](https://github.com/windwp/nvim-ts-autotag) which is language agnostic, so we recommend to use it instead.

I have used this plugin for a while, but I often encounter some occasional bugs during use, and I don't know why. After that   I switch to use `coc.nvim`, it implements `JsxCloseTag` feature and I didn't encounter bugs in use.

**Comment by PHSix** [comment]
> Just out of curiosity: why not use tsserver completion? If you type `</` then tsserver gives us completion of the jsx tag (like in the image below)
> 
> <img alt="image" width="629" src="https://user-images.githubusercontent.com/35625949/274330409-02c93814-d099-479c-af11-44a3eb3ce699.png">

Because if I use completion to close jsx tag I need to type more keys. Like I need types `</<CR>` afrer `>`, but tsserver have implements `JsxCloseTag` feature and it works well in vscode. So, I think maybe we can do the same work in lua.

**Comment by pmizio** [comment]
I'll put this into my TODO list but I have no eta for it, so if you want dive into this contributions are welcome.

**Comment by PHSix** [comment]
> I'll put this into my TODO list but I have no eta for it, so if you want dive into this contributions are welcome.

Yes , I have forked this repo and try complete this feature. Btw, I am currently encountering an issue where the TSServer server is not returning messages to me, and I have not yet found any methods to troubleshoot my error.
