### ISSUE TITLE
How to set the “locale” option in ”initializationoptions“？

### ISSUE THREAD

**Issue by kola-web** [pmizio/typescript-tools.nvim#180]

**Comment by pmizio** [comment]
Currently there is no option to do that. Locale is hardcoded [here](https://github.com/pmizio/typescript-tools.nvim/blob/47c0461f652b90bc088bcaf6481d488d3b86291e/lua/typescript-tools/process.lua#L44).
But this is quite easy to parameterize, I can do it in some free time but if you want pr's are welcomed.

**Comment by kola-web** [comment]
@pmizio Thank you for your quick reply. I will try to familiarize myself with it as much as possible.

**Comment by pmizio** [comment]
@kola-web I just added new option to set locale from user config check out `tsserver_locale` in readme.

**Comment by kola-web** [comment]
@pmizio Thank you very much for your help
