### ISSUE TITLE
Are Path Aliases Supported?

### ISSUE THREAD

**Issue by atomdmac** [pmizio/typescript-tools.nvim#183]
I've defined some path aliases in my `tsconfig.json` file like this:
```json
{
    ...
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"]
    },
    ...
}
```

I then attempt to import them like this:
```typescript
import myStuff from '~/myStuff';
```

However, I continue to see `Cannot find module...` errors when the LSP attaches.  Based on `:LspInfo`, the `root_dir` appears to be set correctly (i.e. to the directory containing my `tsconfig.json`) but I can't tell if it's actually using the config.

My questions are:
1. Are path aliases supported?
2. If so, is there a way to confirm that the config file is actually being used?

**Comment by pmizio** [comment]
1. Yes they are, video from my project:

https://github.com/pmizio/typescript-tools.nvim/assets/4346598/f58994a2-0c4d-4a96-8f23-5c4465868fa3

2. Simplest way is to add following setting to save tsserver logs:
```lua
    require("typescript-tools").setup {
      ...
      settings = {
        ...
        tsserver_logs = "verbose",
      },
    }
```

Then you find `<tmp_dir_of_your_os>/tsserver_syntax.log` file in this logs you find tsconfig loaded by tsserver.

**Comment by atomdmac** [comment]
I'm ashamed to say that this turned out to be a silly configuration mistake in my `tsconfig.json` file.  However, your comment helped me figure that out.  Thank you very much for your help and for this project!
