### ISSUE TITLE
Cannot find tsserver executab , but tserver is available

### ISSUE THREAD

**Issue by LamprosPitsillos** [pmizio/typescript-tools.nvim#186]
![image](https://github.com/pmizio/typescript-tools.nvim/assets/61395246/fdce300a-86d7-4b51-957f-c2b44c841958)![image](https://github.com/pmizio/typescript-tools.nvim/assets/61395246/f96fbe6b-9dc1-4aa3-8305-fc26fdd471f4)
![image](https://github.com/pmizio/typescript-tools.nvim/assets/61395246/fb870876-c3ac-41a8-bf60-7cf377330b46)

Directory:

```console
HY469-fullstack-React/frontend on  main [!?] via  v20.8.0 via  impure (nix-shell-env) 
❯ ls
src             package.json        tsconfig.json       public             index.html
flake.nix       Dockerfile          tsconfig.node.json  package-lock.json  LICENSE
vite.config.ts  tailwind.config.js  postcss.config.js   flake.lock         README.md
```

**Comment by LamprosPitsillos** [comment]
Ofcoure , i will try later to provide one.
For now , installing localy , using `npm i` , having already set up typescript solves this.

**Comment by mrlectus** [comment]
Am also facing this problem, and i don't want to install locally and am also not using nix and i have set the path tsserver_path but it is still not working, i noticed that if i run zsh and then open the file it would work.
