### ISSUE TITLE
can't filter out diagnostics

### ISSUE THREAD

**Issue by simonlearnscoding** [pmizio/typescript-tools.nvim#188]
I am trying to filter out the following diagnostic but its still showing up

  'ComponentDataType' is declared but its value is never read. tsserver (6133) [1, 10]

This is my setup:
    require("typescript-tools").setup {
      settings = {
        handlers = {
          ["textDocument/publishDiagnostics"] = api.filter_diagnostics(
          -- Ignore 'This may be converted to an async function' diagnostics.
            { 6133 }
          ),
        },

**Comment by pmizio** [comment]
@simonlearnscoding `handlers` should be out of `settings` - put it directly in `setup`. Eg.
```lua
require("typescript-tools").setup {
  handlers = {
    ["textDocument/publishDiagnostics"] = api.filter_diagnostics { 6133 },
  },
  settings = {
    -- rest of settings, but not handlers!
  },
}
```

**Comment by pmizio** [comment]
My example should help you. Due to no response closing.

**Comment by winkee01** [comment]
this doesn't work
