### ISSUE TITLE
How to activate the import aliases

### ISSUE THREAD

**Issue by unrealhenry** [pmizio/typescript-tools.nvim#194]
I want to use the importModuleSpecifier function, how do I set it up? For example @/App.css instead of ./App.css

**Comment by unrealhenry** [comment]
hmm, it seems like it still doesn't work even though I've configured it, so I'm having to use vscode

**Comment by pmizio** [comment]
@unrealhenry I checked it and in fact `importModuleSpecifier` isn't responsible for relative/non-relative imports correct one is `importModuleSpecifierPreference`. For me below one is working. If you still want to use it over vscode :D
```lua
require("typescript-tools").setup {
  settings = {
    tsserver_file_preferences = {
      importModuleSpecifierPreference = "non-relative",
    }
  }
}
```

**Comment by unrealhenry** [comment]
thanks u, i fixed!
