### ISSUE TITLE
Why can't I set it up to produce js projects? Can you assist me?

### ISSUE THREAD

**Issue by phonglenus** [pmizio/typescript-tools.nvim#199]
https://github.com/pmizio/typescript-tools.nvim/assets/122294649/b498f090-9db4-496a-9c22-e0974cc8b3c0

**Comment by pmizio** [comment]
@phonglenus You need to use `jsconfig.json` file in your project form me below simple one done the trick:
```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES6",
    "baseUrl": "."
  },
  "exclude": ["node_modules"]
}
```
Full `jsconfig.json` file spec you can find here: https://code.visualstudio.com/docs/languages/jsconfig

**Comment by phonglenus** [comment]
thank you, i had solved it
