### ISSUE TITLE
Erorr when editing with many diagnostics and errors.

### ISSUE THREAD

**Issue by pavkam** [pmizio/typescript-tools.nvim#201]
Basically was doing some refactoring and moving stuff around and everything in my code was in a broken state. And this started poping up until I restarted the LSP.

```
Error executing vim.schedule lua callback: ...cript-tools.nvim/lua/typescript-tools/protocol/utils.lua:78: attempt to index local 'range' (a nil value)
stack traceback:
	...cript-tools.nvim/lua/typescript-tools/protocol/utils.lua:78: in function 'convert_tsserver_range_to_lsp'
	...ypescript-tools/protocol/text_document/folding_range.lua:39: in function <...ypescript-tools/protocol/text_document/folding_range.lua:38>
	vim/shared.lua: in function 'tbl_map'
	...ypescript-tools/protocol/text_document/folding_range.lua:75: in function <...ypescript-tools/protocol/text_document/folding_range.lua:72>
```

**Comment by pmizio** [comment]
@pavkam  Can you give me some reproduction file and tell me what should I delete/move/whatever? I tried to do this on some of my huge files and I just cannot force this to happen.

**Comment by pavkam** [comment]
Sorry for late reply @pmizio. I wish I could replicate this easily. It happened to me 2 times in the last 3 weeks. And it's very hard to reproduce. I will keep trying.

**Comment by pmizio** [comment]
@pavkam I pushed possible fix to this. I added some nil assertions based on your stacktrace it may fix this, but I'm not sure, feel free to reopen this if it still exists. and if it is please paste new stacktrace

**Comment by pavkam** [comment]
Thanks. I've tried a to replicate with folding multiple levels and such and could not replicate after wards. Maybe it was a weird interaction between LSP, nvim-ufo and whatnot. But hopefully a preventive check will make sure it won't happen.

Thanks for looking into it!
