### ISSUE TITLE
commands  integrated with format

### ISSUE THREAD

**Issue by bitterteasweetorange** [pmizio/typescript-tools.nvim#206]
I use `conform` to format, I want to

- add missing imports
- organize imports
- then format

 on save like vscode, but it's not work well.

I used `vite` template to reproduce.

default:
<img width="1073" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/115888595/a01a8d81-c10e-49eb-9742-7edf95c4cda9">

before save:
<img width="898" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/115888595/91101d15-2ab6-4321-8346-ea254326d4e4">

after save:
<img width="934" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/115888595/4a773874-1852-4596-b48b-93d263223bf2">

my config:
```
    local autocmd = vim.api.nvim_create_autocmd
    local Format = vim.api.nvim_create_augroup('Format', { clear = true })
    autocmd('BufWritePre', {
      group = Format,
      pattern = '*.ts,*.tsx,*.jsx,*.js',
      callback = function(args)
          vim.cmd 'TSToolsOrganizeImports'
          vim.cmd 'TSToolsAddMissingImports'
          require('conform').format { bufnr = args.buf }
      end,
    })
```

**Comment by pmizio** [comment]
By default this commands are async so you have race conditions. They have `sync` param to avoid this.
```lua

local autocmd = vim.api.nvim_create_autocmd
    local Format = vim.api.nvim_create_augroup('Format', { clear = true })
    autocmd('BufWritePre', {
      group = Format,
      pattern = '*.ts,*.tsx,*.jsx,*.js',
      callback = function(args)
          vim.cmd 'TSToolsOrganizeImports sync'
          vim.cmd 'TSToolsAddMissingImports sync'
          require('conform').format { bufnr = args.buf }
      end,
    })
```

If you want to use pure lua instead of vimscript injections all commands are exposed from `typescript-tools.api as functions:

https://github.com/pmizio/typescript-tools.nvim/blob/829b5dc4f6704b249624e5157ad094dcb20cdc6b/lua/typescript-tools/api.lua#L49

**Comment by bitterteasweetorange** [comment]
Thank you!
