### ISSUE TITLE
LazyVim installation guide is wrong 

### ISSUE THREAD

**Issue by morhaham** [pmizio/typescript-tools.nvim#209]
edit: please close this.

The dependencies are reversed as with LazyVim we put plugins that depend on the currently configured plugin and not the opposite. As LazyVim's docs says for the dependencies prop:

> A list of plugin names or plugin specs that should be loaded when the plugin loads.

so this is wrong:
```
{
  "pmizio/typescript-tools.nvim",
  dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  opts = {},
}
```
As a fix I would suggest to put `pmizio/typescript-tools.nvim` as dependency of `plenary` and `nvim-lspconfig`

**Comment by zivarah** [comment]
I'm pretty sure this is correct as-is? Disclaimer: I'm very new to NeoVim/Lazy.nvim, but I'm pretty sure my whole setup would be broken if this worked the way you described.

> A list of plugin names or plugin specs that should be loaded when the plugin loads.

I interpreted this as "A list of plugins that must already be loaded in order for this plugin to load".

The [Lazy.nvim packer migration guide](https://github.com/folke/lazy.nvim?tab=readme-ov-file#packernvim) also uses language that makes me think this is correct as-is:

> The dependencies key can be used to group those required plugins with the one that requires them.

**Comment by morhaham** [comment]
> I'm pretty sure this is correct as-is? Disclaimer: I'm very new to NeoVim/Lazy.nvim, but I'm pretty sure my whole setup would be broken if this worked the way you described.
> 
> > A list of plugin names or plugin specs that should be loaded when the plugin loads.
> 
> I interpreted this as "A list of plugins that must already be loaded in order for this plugin to load".
> 
> The [Lazy.nvim packer migration guide](https://github.com/folke/lazy.nvim?tab=readme-ov-file#packernvim) also uses language that makes me think this is correct as-is:
> 
> > The dependencies key can be used to group those required plugins with the one that requires them.

From the docs:

  {
    "hrsh7th/nvim-cmp",
    -- load cmp on InsertEnter
    event = "InsertEnter",
    -- these dependencies will only be loaded when cmp loads
    -- dependencies are always lazy-loaded unless specified otherwise
    dependencies = {
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-buffer",
    },
    config = function()
      -- ...
    end,
  },
