### ISSUE TITLE
on_attach regression

### ISSUE THREAD

**Issue by SvanT** [pmizio/typescript-tools.nvim#217]
It seems like after this commit:
https://github.com/pmizio/typescript-tools.nvim/commit/df64c37e17d8113353d668a82a0ae6ed39b44ba8
you can no longer disable formatting with this config:
```
require("typescript-tools").setup({
  on_attach = function(client)
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentRangeFormattingProvider = false
  end,
})
```

Formatting is run even after disabling it with the above config.

**Comment by pmizio** [comment]
@SvanT I just merged fix for mentioned commit can you check it?

**Comment by SvanT** [comment]
Yep seems to work fine now, thanks for the fast fix and this awesome project in general :)

**Comment by SvanT** [comment]
It seems to work with the bugfix/219 branch

Thanks for the fast fix and this awesome project in general :)
