### ISSUE TITLE
textDocument/rename only support single file.

### ISSUE THREAD

**Issue by chaozwn** [pmizio/typescript-tools.nvim#219]
When I open the first file, the rename functionality is supported. However, when I open any other files afterwards, the rename feature is no longer available.

https://github.com/pmizio/typescript-tools.nvim/assets/51357674/d3deeb38-8609-4c83-840c-be0710a08100

**Comment by chaozwn** [comment]
link: #213. This PR caused the above issue for me, resulting in my LSP functionality only applying to the first file. The LSP features are lost for all subsequent files.

**Comment by chaozwn** [comment]
commit: 13d9dda2fc1ff82ca5a8ced0e1b46e93debac792
works well.

**Comment by pmizio** [comment]
Merged thanks for report
