### ISSUE TITLE
Running prettier formatting and organize imports together is causing corrupted imports

### ISSUE THREAD

**Issue by redsuperbat** [pmizio/typescript-tools.nvim#225]
Hi!
Great project I really like how you are making my life as a developer much easier ❤️ 

I'm having an issue running this on LazyVim together with prettier. I have setup the organize imports command in an `auto_cmd` in neovim but the command interferes with LazyVim:s prettier formatting causing the imports to corrupt and wont compile.

Here is the auto-cmd
```lua
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*.ts*",
  command = ":TSToolsRemoveUnusedImports",
})
```

And I'm just using the LazyVim default prettier plugin:
```lua
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    -- more stuff here...  
})
```

After saving a buffer with an unused imports my file becomes corrupted and does not compile. Any suggestions on what I can do? 
Thanks for your help! 🚀

**Comment by pmizio** [comment]
@redsuperbat For starters try to run organize imports in sync mode by default it runs as async action and it can cause race condition which breaks your file try something like this:
```lua
vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*.ts*",
  command = ":TSToolsRemoveUnusedImports sync", -- added `sync` here
})
```

If it won't help tell me what is your prettier setup, plugin or something which run it. I'll try to help

**Comment by mmirus** [comment]
@redsuperbat I've run into lots of trouble running the various things I want applied automatically on save without them stepping on each other and causing errors. In case it's helpful, here's where I've currently landed, which seems to be working well so far.

I've omitted parts of the below files to focus in on the most relevant bits; let me know if you want the full code

Generally, formatting on save is handled by conform (also sorting Tailwind classes in the process). In the case of TS/JS files, conform uses prettier.

```lua
-- ...

local function sort_tailwind_classes(bufnr)
  -- ... sort TW classes using tailwind-sorter.nvim
end

local format_opts = { lsp_fallback = true, timeout_ms = 2000 }

local function format(bufnr)
  bufnr = bufnr or vim.api.nvim_get_current_buf()
  sort_tailwind_classes(bufnr)

  require("conform").format(vim.tbl_extend("force", format_opts, { bufnr = bufnr }))
end

vim.api.nvim_create_autocmd("BufWritePre", {
  pattern = "*",
  group = vim.api.nvim_create_augroup("FormatOnSave", {}),
  callback = function(event)
    format(event.buf)
  end,
})

-- ...
```

But when typescript-tools / tsserver are set up, I overwrite that autocommand in the buffer where tsserver is attached. `M.setup()` below is provided to mason-lspconfig's handlers for tsserver; that's how it gets invoked when everything is booted up.

This new autocommand runs the commands I want from typescript-tools, then calls the format function, which in turns sorts Tailwind classes and finally formats with prettier via conform. I don't organize imports here, but you could add that.

```lua
local M = {}

-- This group is named the same as the group for autoformatting, so that it
-- replaces the general autocmd with this one which includes the
-- typescript-tools fixes.
local typescript_on_save_augroup = vim.api.nvim_create_augroup("FormatOnSave", {})
-- note this uses the same augroup name as the above conform autocmd 👆👆

local function on_attach(client, bufnr)
  -- ... set up buffer mappings for TSToolsAddMissingImports, etc.

  vim.api.nvim_clear_autocmds({ group = typescript_on_save_augroup, buffer = bufnr })
  vim.api.nvim_create_autocmd("BufWritePre", {
    group = typescript_on_save_augroup,
    buffer = bufnr,
    callback = function(event)
      vim.cmd("TSToolsFixAll sync")
      vim.cmd("TSToolsRemoveUnused sync")

      require("plugins.conform").format(event.buf)
    end,
  })
end

function M.setup(default_config)
  local config = vim.tbl_deep_extend("force", default_config, {
    on_attach = on_attach,
  })
  require("typescript-tools").setup(config)
end

return M

```

**Comment by redsuperbat** [comment]
Thanks for the suggestions. Using `sync` fixed the issue for me. Although restarting the `tsserver` lsp breaks the autocmd for some reason. But that's a different issue.
