### ISSUE TITLE
duplicated diagnostic

### ISSUE THREAD

**Issue by gmdevz** [pmizio/typescript-tools.nvim#226]
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/d68cdad0-e02f-460a-8b78-880dbb841a9c)
good day.. My diagnostics are duplicated when using the **typescript-tools.nvim** _(typescript installed globally via npm)_ and my configs are just as is  on how I installed it using _Lazy_
is that meant to be? Is there a workaround for it?

Thank you in advance.

**Comment by pmizio** [comment]
@gmmoose20 It shouldn't be like that, besides nvim deduplicate same diagnostics from one server. It looks like you have second one which is running for example standard tsserver from lspconfig. Did you disabled lspcnfig one? Please run `:LspInfo` to verify you don't have attached any other typescript server.

**Comment by gmmoose20** [comment]
this is my `:LspInfo`
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/535908a1-2cb5-4594-bad4-f0ff86a5ec10)

as for my lspconfig:
`
tsserver = {
enabled = false
}
`
Is there a way to disable it? may be I just didn't do the right way 😅

**Comment by pmizio** [comment]
If it isn't listed in `:LspInfo` this mean it is correctly disabled. Followup question, you have it duplicated always and every diagnostic message is duplicated or is it accideutialy - happens from time to time?

If it is from time to time it can be connected with https://github.com/pmizio/typescript-tools.nvim/issues/202 this. Stale one message is stale for some reason, which I don't know yet,  and you get duplication. In this case you may try to clear diagnostic using `:lua vim.diagnostic.reset()`. You may also give a shoot this https://github.com/pmizio/typescript-tools.nvim/pull/223 branch and let me know if it helps.

If it is permanent probably it isn't connected to case described previously, so I need more info:
- nvim version
- typescript version
- ideally project to reproduce

**Comment by gmmoose20** [comment]
`nvim -v: NVIM v0.9.5`
`tsc -v: 5.3.3`

I only get the duplicate diagnostic with _typescript-tools.nvim_ but when I remove it and  just use the plain _extras.typescript_ from **Lazyvim** it works just fine.

**Comment by pmizio** [comment]
Weird, I'll install LazyVim distro and check it with your configuration

**Comment by gmmoose20** [comment]
here.. under plugins/lsp.lua

```
  {
    "pmizio/typescript-tools.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    opts = {
       on_attach = on_attach,
        settings = {
          tsserver_file_preferences = {
            includeCompletionsForModuleExports = true,
  
            -- inlay hints
            includeInlayParameterNameHints = "literals",
            includeInlayParameterNameHintsWhenArgumentMatchesName = false,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayVariableTypeHints = true,
            includeInlayVariableTypeHintsWhenTypeMatchesName = false,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayEnumMemberValueHints = true,
          },
          tsserver_format_options = {
            allowIncompleteCompletions = false,
            allowRenameOfImportPath = false,
          },
        },
      },
   },
```

I have my typescript installed via npm globally.

**Comment by pmizio** [comment]
@gmmoose20 ok so i installed lazyvim to check it and fill my understanding of situation, you have both lazyvim's setting `    { import = "lazyvim.plugins.extras.lang.typescript" },` and my plugin in the same time and then you get duplicated diagnostic? Then you eg. comment out lazyvim's setting and still have duplicated diagnostic yes?

If both are true my best bet is delete `typsecript-language-server` from `:Mason`. When it is installed `mason-lspconfig` still bootstrap it and probably becouse of this you get this duplications. To do this go to `:Mason` then press `X`(capital letter) on `typescript-language-server` relaunch nvim and let me know it helps.

**Comment by gmmoose20** [comment]
unfortunately still the same, I did try reinstalling fresh lazyvim and only added `typescript-tools` and still the same it still duplicates the diagnostics.

one thing I notice too is that its saying `tsserver....` in diagnostic line but when I'm using just the typescript plugin from `lazyvim import` it just says `typescript...` and also when I don't disable `tsserver` from `lspconfig` and just have them both, it shows `tsserver...` and `tyescript...` so I'll have three the same diagnostics. That's when I knew that it's something in `typescript-tools` plugin.

**Comment by pmizio** [comment]
@gmmoose20  Can you make some minimal repo with config which presents error? I cannot reproduce it, tried to install lazyvim by cloning it into my `.config/nvim` then I just created `plugins/lsp.lua` then from this file I returned your config posted [here](https://github.com/pmizio/typescript-tools.nvim/issues/226#issuecomment-1900317420) and `typesciript-tools` working correctly no duplications. You can try to follow what I did maybe this show us something. I'm pretty sure it is something in your configuration, because you tell me about 3 different "variables": lazyvim's `{ import = "..." }` thingy, lsp-config(I'm not sure you use it separately) and typescript-tools.
We add `lspconfig` configuration to `typescript-tools` under the hood when calling `setup` so it is possible to some code yours/lazyvim's call it twice.

**Comment by gmmoose20** [comment]
I don't really know why in mine its getting duplicates. 

This is a fresh install Lazyvim.
my config at `/plugins/lsp.lua`:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/1d83ddd2-f129-455d-a995-44ed3d422770)



this what happens when I install `typescript` globally with `:MasonInstall typescript-server-language`
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/bb76e969-b7bf-4602-a888-deaede6b5623)

![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/3a6b3e3d-557e-4bf0-9c2f-8cea76c368e7)
as you can see I have three with the same output, when I remove `typescript-tools` plugin I don't get any duplicates.

**Comment by pmizio** [comment]
oh, I just noticed you are on windows maybe this is some clue i need to check this

**Comment by gmmoose20** [comment]
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/670b42b0-524f-4d58-8959-5fd698941b21)
may be its something to do with the `cmd` ?

**Comment by gmmoose20** [comment]
> ![image](https://private-user-images.githubusercontent.com/62541303/299969302-670b42b0-524f-4d58-8959-5fd698941b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjg0ODcsIm5iZiI6MTcwNjI2ODE4NywicGF0aCI6Ii82MjU0MTMwMy8yOTk5NjkzMDItNjcwYjQyYjAtNTI0Zi00ZDU4LTg5NTktNWZkNjk4OTQxYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDExMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZWY5YjJlM2NiNjNlMjc2MTA2ZjY1ZGIyMzU5ZDdhZmNhYTkzNDRkYWEyOGM0NGI4YWRiMTQwNzU3YjViZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUtDlB0TvZHag8thmqMIbYBx-6YZK1k9dGuBMEWp6lI) may be its something to do with the `cmd` ?

I manage to fix my issue with this config:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/62541303/79737757-6042-4cc8-9226-da3502938332)

I don't get duplicates now. So I think its about that `cmd:` on windows..

hope this helps on debugging the plugin for windows users. :)

**Comment by net** [comment]
For anyone using mason-lspconfig, mason-lspconfig automatically sets up all LSPs installed with Mason. To work around this, you can configure a setup handler that will return early if `server_name == 'tsserver'`. See the mason-lspconfig docs for more info.

**Comment by sp3ctum** [comment]
I had a similar issue where both `typescript-tools` and `tsserver` were launched. Many things were "doubled" such as go to definition adding two tag stack entries (had to Ctrl+t twice to get back), LSP renaming asked the name of the new symbol twice,...

See above for the fix that worked for me - I am not sure I understand what is going on, but hopefully it's helpful.

**Comment by kirylvarykau** [comment]
Same issue for me: 
<img width="1824" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/35407446/505849e4-6070-4bee-a7bd-07145ab734da">

LspInfo: 
<img width="2054" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/35407446/a83639db-8872-4642-a45f-7c01422460d3">

I have latest MacOS and NeoVim. The plugin was install via Mason. 

The workaround from @net seems to work

**Comment by uthmanmoh** [comment]
Can someone provide an example of how to apply the fix from @net? I tried the following but it doesn't seem to be working:
```lua
{
    "williamboman/mason-lspconfig.nvim",
    opts = {
      handlers = {
        function(server_name)
          if server_name == "tsserver" then
            return
          end
        end,
      },
    },
  }
  ```

**Comment by jakubreron** [comment]
When I skip loading `tsserver` with `mason`, I don't have all the syntax highlighting
```lua
{
    "williamboman/mason-lspconfig.nvim",
    opts = {
      handlers = {
        function(server_name)
          if server_name == "tsserver" then
            return
          end
        end,
      },
    },
  }
```

This is my syntax highlighting with `tsserver` skipped (only typescript-tools attached)
![image](https://github.com/pmizio/typescript-tools.nvim/assets/25802053/1a6f6b80-e57b-4506-848f-0e984e3a7b97)

And this is syntax highlighting with both `tsserver` and `typescript-tools` attached
![image](https://github.com/pmizio/typescript-tools.nvim/assets/25802053/43d68d25-ff22-45eb-a016-42878b89a03a)

Skipping the `tsserver` disables a lot of the syntax features, and the code gets harder to read

**Comment by kiuKisas** [comment]
With LazyVim, the culprit for my case was LazyExtra `lang.typescript`. So I disable it for now

**Comment by mbalazy** [comment]
<img width="949" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/49127168/8f609a24-c704-4703-892c-81fb16ae80fc">
<img width="996" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/49127168/7b8060b4-7508-492e-a412-b755df3ca2b5">

I'm still getting duplicated diagnostic, how to properly disable `tsserver?

**Comment by dustypomerleau** [comment]
@mbalazy Make sure that you aren't calling `setup()` for `typescript-tools` or `tsserver` in another location in your config (for example in your setup for `nvim-lspconfig`). This typically happens when the user calls `setup()`, and then `typescript-tools` also calls `setup()` internally, so you end up with 2 instances.

**Comment by mbalazy** [comment]
for Lunarvim users:

- delete `typescript-language-server` from `:Mason`
- add `lvim.lsp.installer.setup.automatic_installation.exclude = { 'tsserver' }` into your `config.lua`
