### ISSUE TITLE
Extra indent when pressing enter in a JSDoc

### ISSUE THREAD

**Issue by MariaSolOs** [pmizio/typescript-tools.nvim#229]
If one opens a JSDoc and presses `<enter>` in code like

```ts
/**| <- Enter here
function foo(n: number) { return n; }
```

Then the cursor and inserted start are preceded by an extra indent:

```ts
/**
    *|
function foo(n: number) { return n; }
```

**Comment by pmizio** [comment]
@MariaSolOs I'm almost sure it isn't connected with this plugin. Indentations and so on is provided by nvim itself or more specifically by tree-sitter(if you have indentation feature enabled). Only things related to formatting/indentation are [range]format requests which aren't invoked automatically.

In my setup indentation working with and without this plugin.

**Comment by MariaSolOs** [comment]
@pmizio Interesting, I don't have Treesitter indentation enabled, so it shouldn't be that. I'll look into my `nvim` indentation settings.

Closing this here then!

**Comment by MariaSolOs** [comment]
For extra context in case anyone encounters this issue in the future: Sounds like I was encountering https://github.com/nvim-treesitter/nvim-treesitter/issues/2544. Weirdly enough, enabling Treesitter indentation for TypeScript/JavaScript files fixed the issue.

**Comment by MariaSolOs** [comment]
> @MariaSolOs Hey could you please take a look at my [post on Reddit](https://www.reddit.com/r/neovim/comments/1aovlfn/extra_indent_is_added_after_multiline_comment_in/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)? 

Idk what you want me to do, I already shared my solution here.
