### ISSUE TITLE
Question: ts-error-translator.nvim support

### ISSUE THREAD

**Issue by andrew-t-james-core** [pmizio/typescript-tools.nvim#243]
Thanks for the dope plugin, was curious if https://github.com/dmmulroy/ts-error-translator.nvim would work out of the box with ts-tools. I tried but to no avail could I seem to get it connect. Happy to contribute as well if a fix is needed.

**Comment by uolot** [comment]
@andrew-t-james-core - thanks for sharing this interesting plugin! Would you mind sharing how you resolved the issue?

**Comment by andrew-t-james-core** [comment]
I wasn't able to, plus I don't think this is the correct project to add this issue so I closed it.  Open issue in ts-error-translator. https://github.com/dmmulroy/ts-error-translator.nvim/issues/19

**Comment by mehalter** [comment]
@uolot `ts-error-translator.nvim` added support for `typescript-tools.nvim` ~10 hours ago: https://github.com/dmmulroy/ts-error-translator.nvim/pull/22

So it just works out of the box
