### ISSUE TITLE
cross-plugin: [Fzf-lua] Error executing 'textDocument/prepareCallHierarchy': timeout

### ISSUE THREAD

**Issue by nyngwang** [pmizio/typescript-tools.nvim#244]
Got an error when using with fzf-lua `:FzfLua lsp_finder` command, which depends on `textDocument/prepareCallHierarchy`. This lsp method is not listed there in your [README](https://github.com/pmizio/typescript-tools.nvim?tab=readme-ov-file#supported-lsp-methods). Just want to know whether this would be supported in the future.

The error message:

```
Error  14:01:40 notify.error [Fzf-lua] Error executing 'textDocument/prepareCallHierarchy': timeout
```

**Comment by 3rd** [comment]
Does workspace/symbol work for you? I always get a timeout on that as well.

**Comment by nyngwang** [comment]
@3rd I didn't try. Now I fallback to the old horse tsserver.

**Comment by KostkaBrukowa** [comment]
@nyngwang can you try if the linked PR helps?
