### ISSUE TITLE
Is this already dead?

### ISSUE THREAD

**Issue by jsilvao** [pmizio/typescript-tools.nvim#247]
Last commit was 2 months ago. Is there any plans of the maintainer to continue work on it?

**Comment by KerberosKomondor** [comment]
Looks like the maintainer was on vacation as of a week ago. 
https://github.com/pmizio/typescript-tools.nvim/pull/240#issuecomment-1962303257
IMO 2 months isn't that bad for side projects but I was reading through PRs to see what was out there and came across that comment.

**Comment by GitMurf** [comment]
Any word on whether the maintainer plans to return to actively updating the project? there are a lot of PRs outstanding.
