### ISSUE TITLE
Integrating with volar 2

### ISSUE THREAD

**Issue by kmoschcau** [pmizio/typescript-tools.nvim#249]
[This commit](https://github.com/neovim/nvim-lspconfig/commit/c9f387f) in nvim-lspconfig mentions that vue integration is now done via a tsserver plugin instead of using volar in take-over-mode. I think I got that working with `typescript-tools.nvim`, by installing `@vue/typescript-plugin` globally and adding this to my setup:

```lua
require("typescript-tools").setup {
  filetypes = {
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",

    "vue", -- This needed to be added.
  },
  settings = {
    tsserver_plugins = {
      -- Seemingly this is enough, no name, location or languages needed.
      "@vue/typescript-plugin",
    },
  },
}
```

From what I can tell I think I go it working, but I am running into [this problem](https://github.com/vuejs/language-tools/issues/3925#issuecomment-1976722072) as well. It seems to only happen in vue files, so it might just as well be volar, that's misbehaving and not typescript-tools.

Is there anything else we need to do for this setup? Also it might be good to add this setup to `typescript-tools.nvim`'s README once vue integration fully works.

**Comment by chaozwn** [comment]
> [This commit](https://github.com/neovim/nvim-lspconfig/commit/c9f387f) in nvim-lspconfig mentions that vue integration is now done via a tsserver plugin instead of using volar in take-over-mode. I think I got that working with `typescript-tools.nvim`, by installing `@vue/typescript-plugin` globally and adding this to my setup:
> 
> ```lua
> require("typescript-tools").setup {
>   filetypes = {
>     "javascript",
>     "javascriptreact",
>     "typescript",
>     "typescriptreact",
> 
>     "vue", -- This needed to be added.
>   },
>   settings = {
>     tsserver_plugins = {
>       -- Seemingly this is enough, no name, location or languages needed.
>       "@vue/typescript-plugin",
>     },
>   },
> }
> ```
> 
> From what I can tell I think I go it working, but I am running into [this problem](https://github.com/vuejs/language-tools/issues/3925#issuecomment-1976722072) as well. It seems to only happen in vue files, so it might just as well be volar, that's misbehaving and not typescript-tools.
> 
> Is there anything else we need to do for this setup? Also it might be good to add this setup to `typescript-tools.nvim`'s README once vue integration fully works.

I am using the same configuration as you.but after create a vue project with `yarn create vite`, i found some mistakes.

![image](https://github.com/pmizio/typescript-tools.nvim/assets/51357674/acd54dca-aea5-4139-9b01-736d94816e70)

**Comment by CofCat456** [comment]
Same problem.

I plan to use tsserver to observe whether the issue occurs in typescript-tools.

**Comment by CofCat456** [comment]
> > [This commit](https://github.com/neovim/nvim-lspconfig/commit/c9f387f) in nvim-lspconfig mentions that vue integration is now done via a tsserver plugin instead of using volar in take-over-mode. I think I got that working with `typescript-tools.nvim`, by installing `@vue/typescript-plugin` globally and adding this to my setup:
> > ```lua
> > require("typescript-tools").setup {
> >   filetypes = {
> >     "javascript",
> >     "javascriptreact",
> >     "typescript",
> >     "typescriptreact",
> > 
> >     "vue", -- This needed to be added.
> >   },
> >   settings = {
> >     tsserver_plugins = {
> >       -- Seemingly this is enough, no name, location or languages needed.
> >       "@vue/typescript-plugin",
> >     },
> >   },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From what I can tell I think I go it working, but I am running into [this problem](https://github.com/vuejs/language-tools/issues/3925#issuecomment-1976722072) as well. It seems to only happen in vue files, so it might just as well be volar, that's misbehaving and not typescript-tools.
> > Is there anything else we need to do for this setup? Also it might be good to add this setup to `typescript-tools.nvim`'s README once vue integration fully works.
> 
> I am using the same configuration as you.but after create a vue project with `yarn create vite`, i found some mistakes.
> 
> ![image](https://private-user-images.githubusercontent.com/51357674/310527464-acd54dca-aea5-4139-9b01-736d94816e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODY0NjQsIm5iZiI6MTcwOTc4NjE2NCwicGF0aCI6Ii81MTM1NzY3NC8zMTA1Mjc0NjQtYWNkNTRkY2EtYWVhNS00MTM5LTliMDEtNzM2ZDk0ODE2ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA0MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNzk4OGY0ZTdkZmE0ZTljNmRjN2M2ZDAwNDFhMDVhYzQyMzNlMTgzOGMxYjdlN2FjZTEwYmIzNzI4MzhhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKzlFjvxxzrkw85NtPlybWHpwy5xAaZrj-3vE-oMYt4)

Same problem.

I plan to use tsserver to observe whether the issue occurs in typescript-tools.

**Comment by chaozwn** [comment]
link: https://github.com/pmizio/typescript-tools.nvim/issues/250

**Comment by catgoose** [comment]
You can now use takeover mode again in volar v2

**Comment by chaozwn** [comment]
> You can now use takeover mode again in volar v2

If you could tell us the method, we would be very grateful.

**Comment by CofCat456** [comment]
> > 現在您可以在 volar v2 中再次使用接管模式
> 
> 如果您能告訴我們方法，我們將不勝感激。

volar = {
  filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
  init_options = {
    vue = {
      hybridMode = false,
    },
  },
 },
 
 But I still hope this issue can be resolved. I prefer a hybridMode.

**Comment by chaozwn** [comment]
> > > 現在您可以在 volar v2 中再次使用接管模式
> > 
> > 
> > 如果您能告訴我們方法，我們將不勝感激。
> 
> ```
> volar = {
>   filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue' },
>   init_options = {
>     vue = {
>       hybridMode = false,
>     },
>   },
>  },
> ```
> 
> But I still hope this issue can be resolved. I prefer a hybridMode.

Does this mean we need to give up the typescript-tools.nvim plugin and use volar exclusively?

**Comment by chaozwn** [comment]
Or does it mean that typescript-tools works only with TypeScript files, while vue files are handled by volar?

**Comment by CofCat456** [comment]
> Or does it mean that typescript-tools works only with TypeScript files, while vue files are handled by volar?

Turning off hybridMode means reverting to the old version 1.8 mode, where takeover mode needs to be enabled for Volar to handle TS and Vue files.

Re-importing the TS server is due to some unresolved compatibility issues. Perhaps for now, discontinuing hybridMode can lead to a better development experience, but hybridMode is what Volar aims for in the future.

I prefer using tsserver or typescript-tools + Volar for development.

**Comment by catgoose** [comment]
> > Or does it mean that typescript-tools works only with TypeScript files, while vue files are handled by volar?
> 
> Turning off hybridMode means reverting to the old version 1.8 mode, where takeover mode needs to be enabled for Volar to handle TS and Vue files.
> 
> Re-importing the TS server is due to some unresolved compatibility issues. Perhaps for now, discontinuing hybridMode can lead to a better development experience, but hybridMode is what Volar aims for in the future.
> 
> I prefer using tsserver or typescript-tools + Volar for development.

I would prefer to use typescript-tools as well, but when I use hybridMode with typescript-tools I have the issue described here:

https://github.com/pmizio/typescript-tools.nvim/issues/250

**Comment by mcchrish** [comment]
You can temporarily disable semantic token for the client until it's fixed.
```lua
client.server_capabilities.semanticTokensProvider = false
```

**Comment by catgoose** [comment]
> You can temporarily disable semantic token for the client until it's fixed.
> 
> ```lua
> client.server_capabilities.semanticTokensProvider = false
> ```

When I do that I get no tsserver diagnostic:

![image](https://github.com/pmizio/typescript-tools.nvim/assets/21010072/dcafc402-4b64-43fb-95a4-e2580dbbcc50)

**Comment by mcchrish** [comment]
@catgoose you can try out vtsls if you don't mind changing a tool. https://github.com/yioneko/vtsls/issues/148#issuecomment-2015051938

**Comment by catgoose** [comment]
> @catgoose you can try out vtsls if you don't mind changing a tool. [yioneko/vtsls#148 (comment)](https://github.com/yioneko/vtsls/issues/148#issuecomment-2015051938)

Thanks I will try it out!

**Comment by CofCat456** [comment]
Can temporarily solve the problem

```
on_attach = function(client)
  client.server_capabilities.semanticTokensProvider = false
end,
```

But I still hope @pmizio  can take some time to look into these issues 🙏

**Comment by KostkaBrukowa** [comment]
Hey! I've fixed semantic tokens issue. Is there anything else that is wrong with with vue? You can check out linked PR

**Comment by 9mm** [comment]
I'm new to typescript (but not neovim/lsps, etc)... What exactly do I have to do to get this working with a fresh nuxt 3 project?

This is my config:

```lua
return {
  "pmizio/typescript-tools.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "neovim/nvim-lspconfig",
  },
  config = function()
    require("typescript-tools").setup({
      filetypes = {
        "javascript",
        "typescript",
        "vue",
      }
    })
  end,
}
```

I can see popups if I do `K` to view info

<img width="475" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/1386207/3cdaf7d3-dc69-47f3-a336-3630d87d5871">

But do I have to do anything to show errors?

Right now they show in `vue-tsc`, but they dont show in my editor

<img width="548" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/1386207/9a7a3489-d232-41fc-bb46-b79c0e28d8d7">

**Comment by Drew-Daniels** [comment]
@9mm You shouldn't need to, here's my config. I've also installed `@vue/typescript-plugin` globally with `npm` and `volar` with [mason.nvim](https://github.com/williamboman/mason.nvim) & [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim).

```lua
require("mason-lspconfig").setup({
	ensure_installed = {
                -- ...
		"volar",
                -- ...
	},
})

local capabilities = require("cmp_nvim_lsp").default_capabilities()
local lspconfig = require("lspconfig")
local servers = {
        -- ...
	"volar",
        -- ...
}
for _, lsp in ipairs(servers) do
	lspconfig[lsp].setup({
		capabilities = capabilities,
	})
end

require("typescript-tools").setup({
	filetypes = {
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"vue",
	},
	settings = {
		capabilities = capabilities,
		root_dir = root_pattern_exclude({
			root = { "package.json" },
			exclude = { "deno.json", "deno.jsonc" },
		}),
		single_file_support = false,
		tsserver_plugins = {
			"@vue/typescript-plugin",
		},
	},
})
```

![image](https://github.com/user-attachments/assets/0ce4881d-7a4c-48dc-bc5b-2e2bd3fec124)

You might try running `:LspInfo` to see if `typescript-tools` is running on that buffer and not some other language server?

**Comment by 9mm** [comment]
thanks @Drew-Daniels ! it was actually 2 separate issues in volar and some other plugin that were both fixed simultaneously. just bad luck would have it that it was the DAY that i switched over, so i thought that it was something in my config. works perfect now!

**Comment by nevenduranec** [comment]
Anyone got vue_ls working? Volar doesn't exist anymore, and i get `Could
not find ts_ls or vtsls lsp client, required by vue_ls`.

**Comment by 9mm** [comment]
@nevenduranec yes mine works fine:

```
        vue_ls = {
          filetypes = { "vue" },
        },
```

heres how i configure typescript tools

```
    "pmizio/typescript-tools.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "neovim/nvim-lspconfig",
    },
    ft = {
      "javascript",
      "typescript",
      "vue",
    },
    config = function()
      require("typescript-tools").setup({
        filetypes = {
          "javascript",
          "typescript",
          "vue",
        },
        settings = {
          separate_diagnostic_server = true,
          expose_as_code_action = "all",
          tsserver_max_memory = "auto",
          tsserver_plugins = {
            "@vue/typescript-plugin",
          },
        },
      })
    end,
  },
```
