### ISSUE TITLE
can't find tsserver on nixos

### ISSUE THREAD

**Issue by liyjii** [pmizio/typescript-tools.nvim#252]
Hello,I'm currently trying to use it in my nixos.
But when I open a ts project,it warns me that spawning tsserver failed.
I tried using 
`tsserver_path = "/nix/store/n3nczhyz5aqxwjkq2qcn966r17l4ah3i-typescript-5.4.2/lib/node_modules/typescript/lib/tsserver.js",
`
but it doesn't work with same error.

**Comment by 0xTux** [comment]
having the same issue with nixos
