### ISSUE TITLE
It uses too much ram when opening JS files

### ISSUE THREAD

**Issue by mrlectus** [pmizio/typescript-tools.nvim#256]
This only happens when i open Javascript files and not typescript. This is a project with a single Javascript file and no node_module, so why eating so much Ram?
![screenshot_2024-03-31T17:24:38](https://github.com/pmizio/typescript-tools.nvim/assets/25666658/3036ebad-5ed8-44f7-804e-95e62a52a6c7)

This is my config
```lua
require("typescript-tools").setup({
  settings = {
    code_lens = "all",
  },
})
```

**Comment by gmr458** [comment]
The README already tell you that CodeLens is a experimental feature, even in VSCode is experimental, because it might hit performance of server.

**Comment by mrlectus** [comment]
> The README already tell you that CodeLens is a experimental feature, even in VSCode is experimental, because it might hit performance of server.

That was not the problem. The problem was that i didn't include a jsconfig file
