### ISSUE TITLE
How to configure code completion, such as integrating with the nvim-cmp plug-in

### ISSUE THREAD

**Issue by HeJiaJunPan** [pmizio/typescript-tools.nvim#258]
I read the documentation carefully, but there is nothing in the documentation about how to configure code completion.

**Comment by mangelozzi** [comment]
I have the same problem, I also use nvim-comp, and had it set to only show completions if at least 3 chars are type:

```lua
local cmp = require('cmp')
cmp.setup({
    preselect = cmp.PreselectMode.None,
    completion = {
        keyword_length = 3,  -- Min word length before showing result
     },
}
```

With typesript-tools it pops up immediately upon pressing dot

**Comment by 0xblur** [comment]
Mine shows no LSP completions with typescript-tools.

**Comment by KostkaBrukowa** [comment]
This plugin implements LSP and it uses native LSP methods to provide completions. If you want to use typescript tools with cmp you should take a look at https://github.com/hrsh7th/cmp-nvim-lsp
