### ISSUE TITLE
Tsserver is launched twice in a project

### ISSUE THREAD

**Issue by victorkamoto** [pmizio/typescript-tools.nvim#260]
I'm using LazyVim, and haven't added the typescript extra. I've only configured typescript-tools.nvim. The typescript-language-server is not installed with mason either. When I open a ts project and open my system monitor, there are two tsserver instances. What could be the problem?

**Comment by igorlfs** [comment]
See the "Configuration" section in the README. You can disable this behavior with

```lua
        settings = {
            separate_diagnostic_server = false,
        }
```

**Comment by victorkamoto** [comment]
Thank you
