### ISSUE TITLE
how to set the rootdir ? 

### ISSUE THREAD

**Issue by tendertree** [pmizio/typescript-tools.nvim#263]
to avoid confilcts with deno. I try to set the root dir to "package.json" 
to apply this method 

```
nvim_lsp.tsserver.setup {
  on_attach = on_attach,
  root_dir = nvim_lsp.util.root_pattern("package.json"),
  single_file_support = false
}
```

However, I don't konw how to set the root dir in default config 

do I load tsserver config seperately ?

**Comment by m3astwood** [comment]
@tendertree there is a solution here that might help you : #132
