### ISSUE TITLE
typescript-tools takes too long to load the project

### ISSUE THREAD

**Issue by franroa** [pmizio/typescript-tools.nvim#264]
Hi there, I have been trying to setup this plugin, and it works well after loading the project, but it takes extremely long to load. Sometimes is even timing out.

I tried with the minimal config in LazyVim and still is not performing well...

My machine is a WSL, by the way.

Could you give me any advice on how to impove the preformance?
Thanks!

**Comment by KostkaBrukowa** [comment]
Is the time of loading the project slower than e.g. https://github.com/typescript-language-server/typescript-language-server? 
Starting tsserver depends largely on project size and it might not be the issue with this plugin

**Comment by franroa** [comment]
You are right, this is a tsserver issue. Thanks!
