### ISSUE TITLE
Bug: Opening Telescopes lsp_references adds 'A' to input

### ISSUE THREAD

**Issue by Lewenhaupt** [pmizio/typescript-tools.nvim#265]
Whenever I have typescript-tools loaded and do `gr` (calls Telescope's builtin lsp_references) an `A` gets added to the input field of Telescope. Remove typescript-tools and then it works as expected.
This is what it looks like:
![swappy-20240513_203230](https://github.com/pmizio/typescript-tools.nvim/assets/7331707/6605591f-b812-4d3a-a2fa-807d849d21e3)

**Comment by Lewenhaupt** [comment]
Could possibly be because tsserver is also installed via Mason. Will check and close of that's the case.

**Comment by Lewenhaupt** [comment]
This was caused because of tsserver also being installed by mason

**Comment by 1orZero** [comment]
Just encountered this issue. I'm so glad I found the solution here. Thank you!

**Comment by 1orZero** [comment]
This issue has resurfaced. Have you encountered this situation again? @Lewenhaupt

**Comment by Lewenhaupt** [comment]
> This issue has resurfaced. Have you encountered this situation again? @Lewenhaupt 
> ![image](https://github.com/user-attachments/assets/86573812-6a5e-4ce8-a099-f10557ac8d00)
> 

Nope, for me it was resolved.

**Comment by 1orZero** [comment]
I just have figured this out. I am using the Lazyvim distribution and the vtsls LSP

To avoid interruptions in the LSP References by vtsls, I have disabled it in the nvim lsp config.

And everything works as expected.


![image](https://github.com/user-attachments/assets/f58caf1b-8dff-4277-8fb4-76aa7a6030a9)
