### ISSUE TITLE
A well-maintained alternative

### ISSUE THREAD

**Issue by kuator** [pmizio/typescript-tools.nvim#273]
To everyone looking for a better maintained alternative, there is is vtsls which is a thin wrapper around tsserver: https://github.com/yioneko/vtsls/commits/main/

**Comment by GitMurf** [comment]
But @kuator that is not a neovim implementation / plugin. How are we supposed to use it?

**Comment by leelhn2345** [comment]
> But @kuator that is not a neovim implementation / plugin. How are we supposed to use it?

https://github.com/yioneko/nvim-vtsls

or download the lsp from mason/coc

**Comment by FelipeJz** [comment]
Man, what happened, i just got here looking for a tsserver alternative

**Comment by GitMurf** [comment]
For the record, I still use typescript tools and have been for a few months and do not have any real problems. I just am hoping it continues to be maintained and some minor iterations 🤞

**Comment by DiviC89** [comment]
Sad to see this go. I'm really hoping for a solid alternative somewhere.

**Comment by GitMurf** [comment]
Why is everyone talking as if this plugin is broken and completely dead?! Yes it appears the maintainer has taken a break but it has only been a few months and the plugin still is working fine for me!

**Comment by sazk07** [comment]
the project is definitely dead. The maintainer should atleast archive the repo and update the Readme.

**Comment by GitMurf** [comment]
> the project is definitely dead. The maintainer should atleast archive the repo and update the Readme.

@sazk07 why do you say that? Has the maintainer said this? What makes you believe it is dead versus the maintainer taking some time away? Open source software is not easy and this happens all the time where a maintainer takes some time away and then comes back later to continue.

**Comment by sazk07** [comment]
> > the project is definitely dead. The maintainer should atleast archive the repo and update the Readme.
> 
> @sazk07 why do you say that? Has the maintainer said this? What makes you believe it is dead versus the maintainer taking some time away? Open source software is not easy and this happens all the time where a maintainer takes some time away and then comes back later to continue.

@GitMurf ; based on the number of open issues + number of unmerged PRs ...

**Comment by moljac024** [comment]
> > > the project is definitely dead. The maintainer should atleast archive the repo and update the Readme.
> > 
> > 
> > @sazk07 why do you say that? Has the maintainer said this? What makes you believe it is dead versus the maintainer taking some time away? Open source software is not easy and this happens all the time where a maintainer takes some time away and then comes back later to continue.
> 
> @GitMurf ; based on the number of open issues + number of unmerged PRs ...

Yup, this sadly looks like it's dead. What are the main differences between vtsls and this? Could it be worthwhile to look into creating a fork of this package?

**Comment by GitMurf** [comment]
@MariaSolOs I believe you have been using this plugin. Do you have any thoughts? Are you still using it or have you switched?

**Comment by MariaSolOs** [comment]
> @MariaSolOs I believe you have been using this plugin. Do you have any thoughts? Are you still using it or have you switched?

I haven't been using TypeScript a lot at work lately (currently focused in Visual Studio so I've been using C#), and so I haven't really looked at the state of my current TypeScript setup.

I do plan on updating it soon though, and I definitely prefer not to depend in unmaintained projects. I might end up just using whatever LazyVim uses (when in doubt, just trust Folke ;) )

**Comment by dustypomerleau** [comment]
In practice, most of the functionality is coming from `tsserver`. Since `vtsls` also uses `tsserver`, and has a Neovim integration already, the transition is fairly easy.

**Comment by GitMurf** [comment]
> > @MariaSolOs I believe you have been using this plugin. Do you have any thoughts? Are you still using it or have you switched?
> 
> I haven't been using TypeScript a lot at work lately (currently focused in Visual Studio so I've been using C#), and so I haven't really looked at the state of my current TypeScript setup.

@MariaSolOs i saw you discussing here in vtsls: https://github.com/yioneko/vtsls/issues/170

Curious if you have used vtsls with neovim yet and your thoughts on it? Thanks!

**Comment by GitMurf** [comment]
@KostkaBrukowa thank you for your recent commits! Are you planning to keep this plugin maintained going forward assuming @pmizio is not able to maintain it right now? Thanks!

**Comment by MariaSolOs** [comment]
> @MariaSolOs i saw you discussing here in vtsls: [yioneko/vtsls#170](https://github.com/yioneko/vtsls/issues/170)
> 
> Curious if you have used vtsls with neovim yet and your thoughts on it? Thanks!

Yes, I recently switched to `vtsls` and I'm quite happy with it. Still experiencing some update delays with diagnostics and inlay hints, but I'm pretty sure this is a TSServer thing.

**Comment by FelipeJz** [comment]
> > @MariaSolOs i saw you discussing here in vtsls: [yioneko/vtsls#170](https://github.com/yioneko/vtsls/issues/170)
> > Curious if you have used vtsls with neovim yet and your thoughts on it? Thanks!
> 
> Yes, I recently switched to `vtsls` and I'm quite happy with it. Still experiencing some update delays with diagnostics and inlay hints, but I'm pretty sure this is a TSServer thing.

Pretty much. I got to understand that our real issue is TSServer that requires a really good one thread processor to work on large codebases. I wonder why there isn't any multithread options, is it even possible?

**Comment by MariaSolOs** [comment]
> Pretty much. I got to understand that our real issue is TSServer that requires a really good one thread processor to work on large codebases. I wonder why there isn't any multithread options, is it even possible?

Well that isn’t TSServer, is JavaScript :D Multithreading would be a feature of the runtime. So it’s not that it’s impossible, just wayyyy out of scope for this plugin (and TypeScript itself).

**Comment by KostkaBrukowa** [comment]
For now I will try to fix new bugs that appear and review and merge new changes but I won't do any more big features for now until I will need some for myself.

**Comment by FelipeJz** [comment]
> > Pretty much. I got to understand that our real issue is TSServer that requires a really good one thread processor to work on large codebases. I wonder why there isn't any multithread options, is it even possible?
> 
> Well that isn’t TSServer, is JavaScript :D Multithreading would be a feature of the runtime. So it’s not that it’s impossible, just wayyyy out of scope for this plugin (and TypeScript itself).

That makes sense. Although my programmer mind tells me that it should be possible to create some type of algorithm to process files individually with workers in some way and then resolve type issues when more files are processed, maybe make a queue with files that import each other and process the ones that do not individually, idk, i'll take a shot at it.

**Comment by rmagatti** [comment]
Just dropping here to thank @pmizio and @KostkaBrukowa for donating their time to work on this plugin for as long as they have. I've used this plugin for quite a while and it has served me well. Open source can be hard and feel a little thankless sometimes, but know your work is much appreciated 🙏
