### ISSUE TITLE
private constructor arguments are not recognized as being read

### ISSUE THREAD

**Issue by codymikol** [pmizio/typescript-tools.nvim#286]
See here, with the private keyword on original, I get the warning that original is declared, but never used.

![image](https://github.com/user-attachments/assets/782f544e-a398-4fd8-8deb-d295a6856574)

Without the keyword this does not happen

![image](https://github.com/user-attachments/assets/da2f92a2-bb53-4b74-9b00-be722f647bc9)

**Comment by KostkaBrukowa** [comment]
Have you checked how it works in other LSP-s? Like vscode or `typescript-language-server`?

**Comment by codymikol** [comment]
Looks like its an issue in other places as well, I see the same behavior in Webstorm.

**Comment by codymikol** [comment]
![image](https://github.com/user-attachments/assets/4bda91c9-83b5-47ed-915a-1fd12b594c7d)

**Comment by KostkaBrukowa** [comment]
But I see that's a typescript error, so you can give a snippet of code and add issue to typescript repo. 
https://www.typescriptlang.org/play/?ssl=27&ssc=1&pln=27&pc=4#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJUUJVdDEEwgAYvAMABvAcleaUHR1ZxkMhMfJiTh4ADaAF0ANzBWdoymoMjsWDoMhKgjzxefXprsxb7c60DTw+HoaCAKOFfF3mbgJAMGXo9xnd8BC-H8mB5O9vn3Q8AF8D1nJ1UAqZcmCVF833Aksc3xTI1EgjC8Hg2ckJKBCgA

**Comment by KostkaBrukowa** [comment]
But on the other side this error is  kind of correct. You declare `private property`, this property is only used in the constructor and is not used anywhere else so you should either remove `private` or use it in some other place other than constructor

**Comment by codymikol** [comment]
You're right, I didn't understand the difference between

```typescript
constructor(foo: string) {}
```
```typescript
constructor(public foo: string) {}
```

I thought that there was a default modifier of `public`, for the first case, but it turns out it's just treated as an argument and not assigned a field on the class. I should just not add a modifier and I get the behavior I'm looking for.

I apologize for my lack of brain wrinkles

![image](https://github.com/user-attachments/assets/c523c194-3833-419b-8487-66dff84be07a)
