### ISSUE TITLE
[question] How to disable autoformatting

### ISSUE THREAD

**Issue by heysokam** [pmizio/typescript-tools.nvim#288]
I honestly feel like I must be blind, but I really can't find the option.
How does one disable formatting on save automatically for this plugin?

**Comment by KostkaBrukowa** [comment]
Example in this issue: #81 

```lua
      require("typescript-tools").setup {
        on_attach = function(client)
          client.server_capabilities.documentFormattingProvider = false
          client.server_capabilities.documentRangeFormattingProvider = false
        end,
      }
```

**Comment by undg** [comment]
Will it disable only typescript-tools to manage lsp formatting?

I wan't to use https://github.com/stevearc/conform.nvim or prettier_d with none-ls instead of typescript-tools for formatting.
