### ISSUE TITLE
Cannot resolve path alias defined in tsconfig.json

### ISSUE THREAD

**Issue by MusherM** [pmizio/typescript-tools.nvim#290]
Here is my problem, I defined path alias as this in ./tsconfig.json
```json
{
  "compilerOptions":{
    ...,
   "baseUrl": "./", 
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
}
}
```
which works smoothly in VSCode, but I found neither tsserver nor this ts-tools can figure it out, as it gives errors like:
<img width="1680" alt="截屏2024-08-09 15 07 18" src="https://github.com/user-attachments/assets/e95e9934-c5a7-4990-8ef4-46c90fb9f6e7">
It seems like no one is caring my tsconfig, but my LspInfo shows:
<img width="1680" alt="截屏2024-08-09 15 07 28" src="https://github.com/user-attachments/assets/45dab651-b8d5-44b3-a78a-c6f449c71d95">
It seems like it gets the correct root path, and thus should get the tsconfig. 
I changed my lsp from tsserver to this, trying to fix it, but failed. It literally drives me crazy. If anyone could provide help, that would be of great help!

**Comment by KostkaBrukowa** [comment]
Can you share link to github repo for me to clone? Maybe I will try to figure something out

**Comment by MusherM** [comment]
Absolutely, https://github.com/MusherM/GuiguMall.git
The master branch by the way, not main

**Comment by MusherM** [comment]
> Can you share link to github repo for me to clone? Maybe I will try to figure something out你能分享到 github repo 的链接让我克隆吗？也许我会试着弄清楚一些事情

Hey, have you figured out anything? I'm digging out the whole Internet and still found nothing similar to my issue

**Comment by KostkaBrukowa** [comment]
Ye. Just looked at it and there isn't a problem with path aliases, but in importing vue files. As you can see in your screenshot only `.vue` files are not visible by tsserver and if you would try to import regular `.ts` files with path alias it would work.

For me adding `"@vue/typescript-plugin"` to plugins in setting worked. You can try this
```
return {
  enabled = true,
  "pmizio/typescript-tools.nvim",
  event = "BufEnter",
  opts = {
    filetypes = {
      "javascript",
      "javascriptreact",
      "javascript.jsx",
      "typescript",
      "typescriptreact",
      "typescript.tsx",
      "vue",
    },
    settings = {
      tsserver_plugins = { "@vue/typescript-plugin" },
    },
  },
}

```

**Comment by MusherM** [comment]
I've added this to my plugin settings, and ran `pnpm install -g @vue/typescript-plugin` to install the plugin, and nothing changes. And yeah, only vue files import fails, I guess it's not a problem with path alias, it's something about using typescript with Vue, I'll continue finding out solutions. 
<img width="1680" alt="截屏2024-08-12 20 52 11" src="https://github.com/user-attachments/assets/5f617f41-18c8-4bed-bbc7-1bb19bf8d050">
