### ISSUE TITLE
bug: settings.complete_function_calls doesn't work as expected

### ISSUE THREAD

**Issue by shyamayadav154** [pmizio/typescript-tools.nvim#291]
```lua
--- mirror of VSCode's `typescript.suggest.completeFunctionCalls`
    complete_function_calls = false,
```

#### Current Behaviour
on false: imports the function with parentheses ( ) 
on true: has no issues

#### Expected Behaviour or vscode behaviour with same setting
on false: imports the function without parentheses

This setting causes react functional component to import with the parentheses and no way to fix it right now

**Comment by KostkaBrukowa** [comment]
I think it's duplicate of https://github.com/pmizio/typescript-tools.nvim/issues/239. For now a PR to solve is open, but author haven't made any progress for some time

**Comment by shyamayadav154** [comment]
apologies for not checking, and thank you for the info
