### ISSUE TITLE
nvim-lspconfig pushed a breaking change

### ISSUE THREAD

**Issue by TakenMC** [pmizio/typescript-tools.nvim#295]
They have changed the setup function to use ts_ls instead of "tsserver"
https://github.com/neovim/nvim-lspconfig/commit/bdbc65aadc708ce528efb22bca5f82a7cca6b54d

**Comment by ngynkvn** [comment]
why was this closed?

**Comment by TakenMC** [comment]
i didnt notice the error came from mason-lspconfig

**Comment by devth** [comment]
Please re-open. This prevents `TSToolsOrganizeImports` from working, e.g.:

```
Error executing Lua callback: .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:669: not found: "typescriptTools/organizeImports" request handler for client "ts_ls".                
stack traceback:                                                                                                                                                                               
        [C]: in function 'assert'                                                                                                                                                              
        .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:669: in function 'request'   
```

**Comment by ehaynes99** [comment]
That command works ok for me.

This plugin doesn't actually reference any of the `lspconfig` values by name, and when it [looks up the installation from mason](https://github.com/pmizio/typescript-tools.nvim/blob/f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7/lua/typescript-tools/tsserver_provider.lua#L125), it does so by file path, which is still `typescript-language-server`.

`ts_ls` shouldn't actually be configured at all if this plugin is used, though... https://github.com/pmizio/typescript-tools.nvim?tab=readme-ov-file#-installation. I.e. if you have a TypeScript file open and run `:LspInfo`, neither `tsserver` nor `ts_ls` should be present. If you manually excluded it somewhere in your lsp config, maybe you need to change the name there?

E.g.
```diff
-if server_name == 'tsserver' then
+if server_name == 'ts_ls' then
   -- configured by `typescript-tools`
   return
 end
```

**Comment by devth** [comment]
@ehaynes99 thanks for posting this! Looks like I have this misconfigured as I do see `ts_ls` in `LspInfo`.
