### ISSUE TITLE
Support for user-provided tsserver.js path

### ISSUE THREAD

**Issue by WesleyT4N** [pmizio/typescript-tools.nvim#47]
Would be useful for projects where tsserver doesn't live in node_modules

**Comment by pmizio** [comment]
@WesleyT4N  @siduck it's implemented https://github.com/pmizio/typescript-tools.nvim/pull/86 here can you test this branch?

**Comment by siduck** [comment]
> @WesleyT4N @siduck it's implemented #86 here can you test this branch?

it works
