### ISSUE TITLE
Unable to resolve global tsserver with custom NODE_PATH

### ISSUE THREAD

**Issue by 3rd** [pmizio/typescript-tools.nvim#50]
Hey, thanks for the project!
When trying to resolve a global tsserver the process.execPath is used, but users can change where they install global packages with `NODE_PATH`.
Using `npm root -g` should be enough to handle all cases.

```lua
-- from:
self.npm_global_path = Path
    :new(vim.fn.system([[node -p "process.execPath"]]):match "^%s*(.-)%s*$")
    :parent()
    :joinpath("..", "lib")

-- to:
self.npm_global_path = Path:new(vim.fn.system("npm root -g")):parent()
```

**Comment by lalitmeeq** [comment]
I installed `typescript-language-server` using `npm` globally. But I am using `nvm` so it's not able to resolve in my case too.

**Comment by pmizio** [comment]
> I installed `typescript-language-server` using `npm` globally. But I am using `nvm` so it's not able to resolve in my case too.

You need `typescript` not `typescript-language-server` to be installed in local or global node_modules.

If it still not working probably this issue is indeed relevant for you also.

**Comment by lalitmeeq** [comment]
@pmizio, Actually I tried installing `typescript` first but somehow it was saying that the file already exists because of `../bin/tsc`. But now I tried with `--force` and it is working fine.

Really it is fast. :+1: I was really looking for something like this.
