### ISSUE TITLE
Can't find tsserver executable

### ISSUE THREAD

**Issue by kuator** [pmizio/typescript-tools.nvim#51]
![Screenshot from 2023-06-22 12-17-08](https://github.com/pmizio/typescript-tools.nvim/assets/25168308/00ef7d7c-397d-4295-8136-c5684b2198e5)

![Screenshot from 2023-06-22 12-17-55](https://github.com/pmizio/typescript-tools.nvim/assets/25168308/b235dc3d-287c-4e93-97f7-43ab716ed6b3)

![Screenshot from 2023-06-22 12-18-15](https://github.com/pmizio/typescript-tools.nvim/assets/25168308/9caf2cbb-9bac-47a3-8092-84a2af626371)

![Screenshot from 2023-06-22 12-18-32](https://github.com/pmizio/typescript-tools.nvim/assets/25168308/3bd0d674-6b14-44ca-a84f-d293ebe7e0e6)

I use asdf for installing nodejs

**Comment by kuator** [comment]
https://github.com/pmizio/typescript-tools.nvim/pull/53

**Comment by pmizio** [comment]
@kuator if I understand correctly pr you mentioned fix your issue?

**Comment by kuator** [comment]
> @kuator if I understand correctly pr you mentioned fix your issue?

Yes

**Comment by pmizio** [comment]
Or is merged to master. Closing
