### ISSUE TITLE
Error executing vim.schedule lua callback: ... attempt to index local 'request' (a nil value)

### ISSUE THREAD

**Issue by ecosse3** [pmizio/typescript-tools.nvim#54]
Hi, I have the following error when trying to autocomplete anything related to TypeScript. It mostly happens for couple first times after file is opened. I didn't have this issue ever before switching to `typescript-tools.nvim`.

```vim
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1518: attempt to index local 'request' (a nil value)
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1518: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

My `lazy.nvim` setup for plugin:

```lua
{
  "pmizio/typescript-tools.nvim",
  lazy = false,
  dependencies = {
    "nvim-lua/plenary.nvim",
    "neovim/nvim-lspconfig",
  },
  opts = {
    tsserver_file_preferences = {
      includeInlayParameterNameHints = "all",
      includeInlayParameterNameHintsWhenArgumentMatchesName = false,
      includeInlayFunctionParameterTypeHints = true,
      includeInlayVariableTypeHints = false,
      includeInlayPropertyDeclarationTypeHints = true,
      includeInlayFunctionLikeReturnTypeHints = false,
      includeInlayEnumMemberValueHints = true,
    },
    settings = {
      tsserver_plugins = { "@styled/typescript-styled-plugin" },
    },
  },
},
```

When I didn't have `lazy = false` the `typescript-tools` haven't been attached to file automatically, even with `ft = { "typescript", "typescriptreact" }`.

Neovim Version: `NVIM v0.10.0-dev-551+ge27377e33`

`typescript` is installed in project as well globally via `npm` for each version I have with `fnm` (v16, v18) and in `pnpm` globals too (for projects with pnpm).

**Comment by pmizio** [comment]
Can you provide some minimal config? I cannot reproduce that, it is probably conflict with some other plugin or something in your config :/

**Comment by pmizio** [comment]
@MurdeRM3L0DY I'm sure this isn't case nvim request only one server and need only one response, I working with this routing strategy for months and no such thing happend to me. Problem is probably somewhere else, but I need some config to reproduce issue. Then I probably will be able to fix this.

**Comment by ecosse3** [comment]
Adding `separate_diagnostic_server` as `false` fixed the issue. It starts correctly with `lazy = false` by default without any errors.

```lua
  settings = {
    separate_diagnostic_server = false,
  }
 ```
 
 Anyway, I think it would be better to spawn other diagnostic servers at least for performance. My config is pretty complex, I have many other LSP clients attached to TypeScript files (tailwindcss, eslint, null-ls, emmet_ls, graphql), but I am not sure if this can be related. I will try to work later on minimal config to reproduce this.

**Comment by pmizio** [comment]
Weird I run 2 servers daily so it somehow works, minimal reproduce config will definitely help solve this issue

**Comment by MurdeRM3L0DY** [comment]
You were right, The issue seems to be from one of my installed plugins: `nvim-navic` with `separate_diagnostic_server` option set to true

**Comment by pmizio** [comment]
Hmm good to know my colleague from work tell me about other issue with this plugin [here](https://github.com/pmizio/typescript-tools.nvim/issues/10) barbecue use navic under the hood so there is "something no yes" with it. But this is some clue to resolve this.
FYI: @KostkaBrukowa

**Comment by pmizio** [comment]
Ok they are some solid clues, we look into it :) I personally don't use any of this plugins so I don't have chance to bump into that.

**Comment by MurdeRM3L0DY** [comment]
@pmizio Could you please explain how to read logs from the servers?

**Comment by pmizio** [comment]
@MurdeRM3L0DY they are two "level" of logs:
1. plugin send some logs to `:LspLog` but you should lower level of it because most of them are traces
2. tsserver logs enabled by [this](https://github.com/pmizio/typescript-tools.nvim/blob/1a1fc8fcc498ade3adf8b251e930abb2eb5b7983/lua/typescript-tools/config.lua#L49) property - they live in temp folder as `tsserver_syntax.log` and `tsserver_semantic.log` files

**Comment by MurdeRM3L0DY** [comment]
right, I forgor to set log level to trace

**Comment by KostkaBrukowa** [comment]
I found (at least for me) that this error does not show up on stable version. I only get this error on nightly. I will look into this

**Comment by KostkaBrukowa** [comment]
@ecosse3 @MurdeRM3L0DY can you take a look at the PR I've made and verify if its working?

**Comment by MurdeRM3L0DY** [comment]
@KostkaBrukowa Yup, that seems to fix it though I can't seem to wrap my head around why it fixes it. Could you briefly explain please? thanks.

**Comment by ecosse3** [comment]
@KostkaBrukowa Yes, looks like it is fixed now. I don't have any errors, thank you! <3

tsserver is much faster now 😮

**Comment by pmizio** [comment]
@MurdeRM3L0DY So, as you know, we have two servers running, each with its dedicated request queue. This queue determines the ID of the request passed to nvim internals. The problem arises when the ID ranges at the start are close and can overlap, causing nvim to receive duplicated requests. This initiates a race condition, where the first completed request deletes metadata in nvim internals, resulting in an error being thrown.
I hope I have explained it enough.

**Comment by MurdeRM3L0DY** [comment]
Yeah, that makes sense! Awesome!
