### ISSUE TITLE
VS Code provides parentheses completion for javascript

### ISSUE THREAD

**Issue by kuator** [pmizio/typescript-tools.nvim#56]
There is a `javascript.suggest.completeFunctionCalls` setting: https://stackoverflow.com/a/60126232

**Comment by KostkaBrukowa** [comment]
This is my current behavior in my editor:

https://github.com/pmizio/typescript-tools.nvim/assets/35625949/a615250c-ed65-433c-9df8-5404e5d06408

I think that this behavior could be enabled by some other plugin (but I don't know which one does this)

**Comment by carlosflorencio** [comment]
Probably cmp with nvim-autopairs? https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#nvim-autopairs

**Comment by kuator** [comment]
> This is my current behavior in my editor:
> Screen.Recording.2023-06-22.at.16.27.25.mov
> 
> I think that this behavior could be enabled by some other plugin (but I don't know which one does this)

My current setup with [vtsls](https://github.com/yioneko/vtsls) which is a thin wrapper around tsserver. As you can see, it's not just parentheses that it completes, but also the arguments.

![Peek 2023-06-22 21-05](https://github.com/pmizio/typescript-tools.nvim/assets/25168308/8badca2c-a8f1-43a8-87be-4bc9de33d5e1)

`vtsls` implements  `javascript.suggest.completeFunctionCalls`

**Comment by pmizio** [comment]
Lsp snippets are supported by this plugin I thing there is some magic switch to enable advanced ones. But unfortunately for now I don’t know where it is. I need to look for that in vscode codebase - what is happening when you tick this checkbox

**Comment by pmizio** [comment]
Yes, it looks like this is some vscode magic, but I look into that, maybe it works over some tsserver api and can be reimplemented. For now I lacking knowledge about this to say more or provide final answer about it is even doable

**Comment by llllvvuu** [comment]
`tsserver` does not serve function snippets in the completion list. You have to construct it in resolve. In practice that means you'll never get something this nice like lua:
<img width="388" alt="Screenshot 2023-07-23 at 3 34 01 AM" src="https://github.com/pmizio/typescript-tools.nvim/assets/5601392/8bab39c3-06d9-4508-850e-2e8fc90bd38f">
You'll get this instead:
<img width="1298" alt="Screenshot 2023-07-23 at 3 41 48 AM" src="https://github.com/pmizio/typescript-tools.nvim/assets/5601392/108de618-9bc3-4e18-926a-c92f4a998465">
(the parameters aren't previewed in the cmp menu, but you do get the doc and the ghost text of the one you've got selected)

Anyways I've copied `typescript-language-server`'s implementation, hope it helps: #116

**Comment by pmizio** [comment]
@kuator If you still interested feature is implemented thanks to @llllvvuu!
Feature is disabled by default, you can enable this by https://github.com/pmizio/typescript-tools.nvim/blob/bdc5878c3c2ad172d0e0e6e29da726b2fdd6e2fd/README.md?plain=1#L142

**Comment by kuator** [comment]
Awesome, thank you!
