### ISSUE TITLE
[Request] Add missing imports command

### ISSUE THREAD

**Issue by carlosflorencio** [pmizio/typescript-tools.nvim#57]
Can you add a similar command to `TypescriptAddMissingImports` in [typescript](https://github.com/jose-elias-alvarez/typescript.nvim)?

Thanks!

**Comment by KostkaBrukowa** [comment]
Tsserver does not natively support `TypescriptAddMissingImports` so some more work would be needed here, but its nice feature to have. 
Also it would be nice to have `TypescriptRemoveUnused` and `TypescriptFixAll` as well, because it would be very similar thing to implement as missing imports

**Comment by KostkaBrukowa** [comment]
@carlosflorencio if you want you can take a look at the linked PR. There aren't docs yet but the commands are:
  "TSToolsRemoveUnused"
  "TSToolsAddMissingImports"
  "TSToolsFixAll"

**Comment by carlosflorencio** [comment]
Tested the `TSToolsAddMissingImports` cmd and seems to work fine :), thanks for the effort!

**Comment by pmizio** [comment]
Merged into master
