### ISSUE TITLE
[bug] Error in setup

### ISSUE THREAD

**Issue by vitaliydolbilov** [pmizio/typescript-tools.nvim#59]
When I call `require("typescript-tools").setup({})`

I get the following error - 

```
E5113: Error while calling lua chunk: ...gged/typescript-tools.nvim/lua/typescript-tools/init.lua:45: attempt to call field 'setup' (a nil value)
stack traceback: ...gged/typescript-tools.nvim/lua/typescript-tools/init.lua:45: in function 'setup'
```

I'm using vim-plug for plugins - have plenary & nvim-lspconfig defined before typescript-tools

`tsc -v` -> Version 4.7.2
`nvim -v` -> NVIM v.0.8.3
`node -v` -> v16.16.0

And `lspconfig.tsserver.setup({})` (the nvim-lspconfig way) was working fine before and I did remove it

Thanks!

**Comment by pmizio** [comment]
It may be connected with vim-plug I never tested plugin with this package manager.

**Comment by simoneeti** [comment]
Same here!

**Comment by FelipeSharkao** [comment]
I've been poking at the code. I added a this right before the [setup call](https://github.com/pmizio/typescript-tools.nvim/blob/master/lua/typescript-tools/init.lua#L45):

```lua
  print(vim.inspect(lspconfig[plugin_config.plugin_name]))
```

The result was this:

```
{
  _setup_buffer = <function 1>,
  commands = <1>{},
  document_config = {
    commands = <table 1>,
    default_config = {
      cmd = <function 2>,
      filetypes = { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
      root_dir = <function 3>,
      single_file_support = true
    }
  },
  name = "typescript-tools",
  setup = <function 4>
}
{
  default_config = {
    cmd = <function 1>,
    filetypes = { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
    root_dir = <function 2>,
    single_file_support = true
  }
}
Erro detectado ao processar /home/felipe/Downloads/minimal-cfg.lua:
E5113: Error while calling lua chunk: ...lazy/typescript-tools.nvim/lua/typescript-tools/init.lua:47: attempt to call field 'setup' (a nil value)
stack traceback:
	...lazy/typescript-tools.nvim/lua/typescript-tools/init.lua:47: in function 'setup'
	/home/felipe/Downloads/minimal-cfg.lua:39: in main chunk
```

It seems that `require("typescript-tools").setup` is being called twice, so the second one doesn't hit [lspconfig.configs.__newindex](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L26)

**Comment by pmizio** [comment]
@FelipeSharkao Thanks for catching this!
@simoneeti @vitaliydolbilov Can you retest this it's merged to master now!

**Comment by simoneeti** [comment]
working now! thanks
