### ISSUE TITLE
Cannot find tsserver for nvs installed nodejs or yarn workspace projects

### ISSUE THREAD

**Issue by TisnKu** [pmizio/typescript-tools.nvim#60]
Thanks for this plugin. Tsserver unstability issue has been bothering me for a long time.

When I try to setup and I find the "Cannot find tsserver executable" error.
I added some logs in `tsserver_provider.lua` and here is the result:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/10512841/e319c931-e2c6-4939-93ec-3d84b74acb4b)

I used nvs to manage my nodejs and my project is using yarn workspace. Coincidentally, none of these 2 matches the default tsserver lookup path.

For nvs installed nodejs on Windows, global path to tsserver should be:
```
  self.npm_global_path = Path
      :new(vim.fn.system([[node -p "process.execPath"]]):match "^%s*(.-)%s*$")
      :parent()
      ---:joinpath("..", "lib") // remove this line
  local tsserver_path = self.root_dir:joinpath("node_modules", "typescript", "lib", "tsserver.js")
```

For mono repo using yarn workspace, the tsserver should be in the node_modules of git root instead of the folder for the nearest tsconfig or package json.

**Comment by pmizio** [comment]
It's probably connected with https://github.com/pmizio/typescript-tools.nvim/issues/61
I just forgot about testing plugin on windows 😅

**Comment by MariaSolOs** [comment]
@pmizio I'm running into the same issue. Moreover, I don't think this is related to the package manager or the operating system because I'm on MacOS and testing your plugin in a project using npm.

That being said, I might be stress-testing your plugin hehe because I'm using it in TypeScript itself :D My "simple" repro is to open [this file](https://github.com/microsoft/TypeScript/blob/f9cf8216c6e9e1339a79e81d772799190c10fa49/src/services/refactors/inlineVariable.ts). Note that the existing Mason plugin doesn't have this issue.

**Comment by pmizio** [comment]
Oh nice I suppose typescript doesn't depend on typescript. So probably local resolution fails. What about global installation? Can you provide more context?

**Comment by pmizio** [comment]
@TisnKu Can you give [this](https://github.com/pmizio/typescript-tools.nvim/pull/53) a test it looks like may help you with global path resolution.

**Comment by MariaSolOs** [comment]
> Oh nice I suppose typescript doesn't depend on typescript. So probably local resolution fails. What about global installation? Can you provide more context? @MariaSolOs

Weirdly enough, TypeScript does depend on itself: https://github.com/microsoft/TypeScript/blob/f7e4f809acaea6b1b247ed05b2b7873d4546ab9e/package.json#L83

**Comment by MariaSolOs** [comment]
> @TisnKu @MariaSolOs Now, the plugin should do a better job of resolving the path to tsserver(in mentioned pr). If you have time, please take a look. Tested on typescript repo itself 😄

I'm still having the same error...
<img width="1184" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/62502207/acd69496-ca59-4a72-9170-e5124bb541ef">

**Comment by MariaSolOs** [comment]
My configuration is:
```lua
local servers = {
    lua_ls = {
        settings = {
            Lua = {
                workspace = { checkThirdParty = false },
                telemetry = { enable = false },
                hint = { enable = true },
            },
        },
    },
    -- Markdown.
    marksman = {},
    -- TOML (mostly used for rust).
    taplo = {},
}

-- Global diagnostic setup.
-- Show a severity icon as the prefix for the virtual text and
-- disable the signs in the gutter.
vim.diagnostic.config {
    virtual_text = {
        source = 'if_many',
        prefix = function(diagnostic)
            local icons = require('helpers.icons').diagnostics
            for d, icon in pairs(icons) do
                if diagnostic.severity == vim.diagnostic.severity[d:upper()] then
                    return icon
                end
            end
        end,
    },
    signs = false,
}

local nmap = function(lhs, rhs, desc, bufnr)
    require('helpers.keybindings').nmap(lhs, rhs, { buffer = bufnr, desc = desc })
end

local on_attach = function(buf_client, bufnr)
    nmap('<leader>c', ':Lspsaga code_action<cr>', 'Code action', bufnr)
    nmap('<leader>o', ':Lspsaga outline<cr>', 'Toggle outline', bufnr)
    nmap('<leader>r', ':Lspsaga rename<cr>', 'Rename', bufnr)

    nmap('<leader>ss', require('telescope.builtin').lsp_document_symbols, 'Search document symbols', bufnr)
    nmap('<leader>sw', require('telescope.builtin').lsp_dynamic_workspace_symbols, 'Search workspace symbols', bufnr)

    nmap('gd', ':Lspsaga goto_definition<cr>', 'Go to definition', bufnr)
    nmap('gr', require('telescope.builtin').lsp_references, 'Go to references', bufnr)
    if buf_client.server_capabilities.implementationProvider then
        nmap('gI', require('telescope.builtin').lsp_implementations, 'Go to implementation(s)', bufnr)
    end
    if buf_client.server_capabilities.typeDefinitionProvider then
        nmap('gt', require('telescope.builtin').lsp_type_definitions, 'Go to type definition(s)', bufnr)
    end

    -- noice deals with the UI.
    nmap('K', vim.lsp.buf.hover, 'Hover', bufnr)

    nmap('[d', ':Lspsaga diagnostic_jump_prev<cr>', 'Previous diagnostic', bufnr)
    nmap(']d', ':Lspsaga diagnostic_jump_next<cr>', 'Next diagnostic', bufnr)

    -- Enable inlay hints if the client supports it.
    if buf_client.server_capabilities.inlayHintProvider then
        vim.api.nvim_set_hl(0, 'LspInlayHint', { fg = '#6272A4', italic = true })
        vim.lsp.buf.inlay_hint(bufnr, true)
    end

    -- Toggle the floating terminal.
    -- NOTE: The <cmd> below is needed to exit terminal mode.
    vim.keymap.set({ 'n', 't' }, '<M-t>', '<cmd>Lspsaga term_toggle<cr>', { desc = 'Toggle floating terminal' })

    -- Create a command `:Fmt` local to the LSP buffer
    vim.api.nvim_buf_create_user_command(bufnr, 'Fmt', function(_)
        vim.lsp.buf.format()
    end, { desc = 'Format current buffer' })

    -- Set up format on save.
    vim.api.nvim_create_autocmd('BufWritePre', {
        group = require('helpers.commands').augroup 'FormatOnSave',
        pattern = { '*.lua', '*.rs' },
        callback = function()
            local buf = vim.api.nvim_get_current_buf()
            local ft = vim.bo[buf].filetype

            -- When a null-ls formatter is available for the current filetype, only null-ls formatters are returned.
            local null_ls = package.loaded['null-ls']
                    and require('null-ls.sources').get_available(ft, 'NULL_LS_FORMATTING')
                or {}
            local clients = vim.lsp.get_active_clients { bufnr = buf }
            local available = {}
            for _, client in ipairs(clients) do
                if
                    client.supports_method 'textDocument/formatting'
                    or client.supports_method 'textDocument/rangeFormatting'
                then
                    if (#null_ls > 0 and client.name == 'null-ls') or #null_ls == 0 then
                        table.insert(available, client.id)
                    end
                end
            end

            if #available == 0 then
                return
            end

            vim.lsp.buf.format {
                bufnr = buf,
                filter = function(client)
                    return vim.tbl_contains(available, client.id)
                end,
            }
        end,
    })
end

return {
    {
        'neovim/nvim-lspconfig',
        event = { 'BufReadPre', 'BufNewFile' },
        dependencies = {
            {
                'williamboman/mason.nvim',
                cmd = { 'Mason', 'LspInstall', 'LspUnInstall' },
                config = true,
            },
            {
                'williamboman/mason-lspconfig.nvim',
                opts = {
                    ensure_installed = vim.tbl_keys(servers),
                },
            },
            {
                'folke/neodev.nvim',
                opts = {
                    -- Types for DAP UI.
                    library = { plugins = { 'nvim-dap-ui' }, types = true },
                },
            },
            -- JSON schemas.
            { 'b0o/SchemaStore.nvim', version = false },
            -- Extra goodies for rust.
            { 'simrat39/rust-tools.nvim' },
            -- "Native" TSServer client.
            {
                'pmizio/typescript-tools.nvim',
                dependencies = 'nvim-lua/plenary.nvim',
                opts = {
                    on_attach = on_attach,
                    settings = {
                        tsserver_file_preferences = {
                            includeInlayParameterNameHints = 'all',
                            includeInlayParameterNameHintsWhenArgumentMatchesName = false,
                            includeInlayFunctionParameterTypeHints = true,
                            includeInlayVariableTypeHints = true,
                            includeInlayVariableTypeHintsWhenTypeMatchesName = false,
                            includeInlayFunctionLikeReturnTypeHints = true,
                        },
                    },
                },
            },
        },
        config = function()
            -- nvim-cmp supports additional completion capabilities, so broadcast that to servers.
            local capabilities = vim.lsp.protocol.make_client_capabilities()
            capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)

            require('mason-lspconfig').setup_handlers {
                function(server)
                    local settings = vim.tbl_extend('force', {
                        capabilities = capabilities,
                        on_attach = on_attach,
                    }, servers[server] or {})

                    require('lspconfig')[server].setup(settings)
                end,
                -- Configure other LSP servers that have a special setup.
                clangd = function()
                    -- Fixes 'warning: multiple different client offset'.
                    local clangd_capabilities = vim.deepcopy(capabilities)
                    clangd_capabilities.offsetEncoding = 'utf-8'

                    require('lspconfig').clangd.setup {
                        capabilities = clangd_capabilities,
                        on_attach = on_attach,
                    }
                end,
                jsonls = function()
                    require('lspconfig').jsonls.setup {
                        capabilities = capabilities,
                        on_attach = on_attach,
                        settings = {
                            json = {
                                schemas = require('schemastore').json.schemas(),
                                validate = { enable = true },
                            },
                        },
                    }
                end,
                rust_analyzer = function()
                    local rt = require 'rust-tools'

                    rt.setup {
                        tools = {
                            -- Disable inlay hints since Neovim now supports them.
                            inlay_hints = {
                                auto = false,
                                show_parameter_hints = false,
                            },
                        },
                        server = {
                            capabilities = capabilities,
                            on_attach = function(client, bufnr)
                                on_attach(client, bufnr)

                                -- Set up extra Rust commands.
                                nmap('K', rt.hover_actions.hover_actions, 'Hover', bufnr)
                                nmap('<leader>Rm', rt.expand_macro.expand_macro, 'Expand macro', bufnr)
                                nmap('<leader>Rr', rt.runnables.runnables, 'Runnables', bufnr)
                                nmap('<leader>Rc', rt.open_cargo_toml.open_cargo_toml, 'Open Cargo.toml', bufnr)
                                require('which-key').register {
                                    ['<leader>R'] = { name = '+rust' },
                                }
                            end,
                            settings = {
                                ['rust-analyzer'] = {
                                    inlayHints = {
                                        -- These are a bit too much.
                                        chainingHints = { enable = false },
                                    },
                                },
                            },
                        },
                    }
                end,
                eslint = function()
                    require('lspconfig').eslint.setup {
                        settings = {
                            format = false,
                        },
                    }
                end,
            }
        end,
    },

    -- Nicer UI.
    {
        'glepnir/lspsaga.nvim',
        cmd = 'Lspsaga',
        dependencies = {
            'nvim-tree/nvim-web-devicons',
            'nvim-treesitter/nvim-treesitter',
        },
        opts = {
            ui = {
                border = 'rounded',
                code_action = '',
            },
            outline = {
                keys = {
                    expand_or_jump = '<cr>',
                },
                auto_resize = true,
            },
            finder = {
                keys = {
                    jump_to = '<Tab>',
                    expand_or_jump = '<cr>',
                },
            },
        },
    },

    -- Use Neovim as a language server.
    {
        'jose-elias-alvarez/null-ls.nvim',
        dependencies = 'nvim-lua/plenary.nvim',
        event = 'VeryLazy',
        config = function()
            local null_ls = require 'null-ls'

            null_ls.setup {
                sources = {
                    null_ls.builtins.code_actions.gitsigns,
                    -- Formatters.
                    null_ls.builtins.formatting.clang_format,
                    null_ls.builtins.formatting.stylua,
                },
            }
        end,
    },
}
```

**Comment by MariaSolOs** [comment]
> @MariaSolOs Oh, you have installed from master, fix is still pr on separate branch, add: `branch = "feat-change-path-resolve-strategy",` to lazy installation instruction for our plugin. And reinstall plugins.

Okay so now the client is attaching, but I'm now running into #59

**Comment by MariaSolOs** [comment]
Okay does this branch have the fix from #54?

**Comment by pmizio** [comment]
Nope I merged them now into branch with fix

**Comment by MariaSolOs** [comment]
> Nope I merged them now into branch with fix

Good news! I just tried it and it works :)

**Comment by pmizio** [comment]
Just merged it to master for all other peeps who may encounter problem but still wait for response from issue author to close this.

**Comment by TisnKu** [comment]
Just tested with latest master, no tsserver anymore. Thank you.

**Comment by siduck** [comment]
@pmizio  i keep getting this error 

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/f80cd330-29f6-4823-b35e-bc64a762afe2)


even tho i have installed typescript-language-server from mason

and its on my path too 

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/ac520844-5d20-4a63-9b40-ad7b1aa4c43f)

**Comment by pmizio** [comment]
Plugin don't use `typescript-language-server` you need to install just `typescript` in local project or globally. Typescript package includes its own language server so:
```
npm i --save-dev typescript # to use local installation
# or
npm i -g typescript # to use glona one

```

**Comment by siduck** [comment]
> Plugin don't use `typescript-language-server` you need to install just `typescript` in local project or globally. Typescript package includes its own language server so:
> 
> ```
> npm i --save-dev typescript # to use local installation
> # or
> npm i -g typescript # to use glona one
> ```

thanks! but the global one doesnt work, 

left one here doenst have typescript installed locally , where as the right one does

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/407454bf-1e76-439a-a087-74f24edf5aa0)

**Comment by pmizio** [comment]
@siduck You can enable neovim lsp trace logs. Then plugin [log paths](https://github.com/pmizio/typescript-tools.nvim/blob/4f4f3874475ea08fbc6ed7a002495bdd24376932/lua/typescript-tools/tsserver_provider.lua#L78) which are checked into `:LspLog`. You can compare it with your actual global tsserver location. You can also share details about this paths and how you have node installed.
You may also run `npm root --global` to check where is your global installation directory.

**Comment by siduck** [comment]
@pmizio lsp log doesnt show anything important, as for my global installation

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/5b040cb0-3366-45ac-b84c-bea82c0a3b0b)

**Comment by pmizio** [comment]
You may also show log output which I described in my previous comment it may be helpful. Now I literally don't know where plugin try to find language server binary

**Comment by siduck** [comment]
> You may also show log output which I described in my previous comment it may be helpful. Now I literally don't know where plugin try to find language server binary

Lsplog just outputs this 
![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/72723ca7-ea39-4dbd-a351-fb76a63d7a31)


also i installed typescript globally by  `npm i -g typescript` 

it even shows up in my shell completions

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/3402a9db-c898-4517-ba61-10ff9c1f3c07)

**Comment by pmizio** [comment]
You need to change log level to trace first `vim.lsp.set_log_level("trace")`

**Comment by siduck** [comment]
> vim.lsp.set_log_level("trace")

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/06e90ad9-9df4-4284-9997-1b9f207baa15)

**Comment by pmizio** [comment]
Can you check this last path? What is wrong with it? I mean checking out what is under it or it's parents. In general you looking for `tsserver.js` file in typescript's package in global installation directory. For me path itself looks good and it is in directory retuned by `npm root -g` so it should work. But if you provide me more information I try to do something.

**Comment by siduck** [comment]
> 

ohh seems like its a path issue after all, i use volta to install nodejs/npm packages and it stored the tsserver.js file here

![image](https://github.com/pmizio/typescript-tools.nvim/assets/59060246/04b859e3-4352-4ca8-9815-09e3dfcd3eb5)

**Comment by pmizio** [comment]
@siduck  Yes it is we have even issue for this https://github.com/pmizio/typescript-tools.nvim/issues/47 I look into this today.

**Comment by siduck** [comment]
> @siduck Yes it is we have even issue for this #47 I look into this today.

thanks man!

**Comment by MariaSolOs** [comment]
> @pmizio Hi, i've just had this problem and i fixed it by instaling the `typescript` package gobally as you recommended. Shouldn't this be in the readme?

@lucasmarinb Global `npm` packages aren't really recommended, and even less with TypeScript. Here it is meant to serve as a workaround, but ideally you should always have a local TypeScript installation (else the project's compilation would depend on the user's machine).

**Comment by pmizio** [comment]
Exactly like @MariaSolOs said. I can help you to resolve this but I need more info about your workspace. Plugin checks for `node_modules` in your project `root_dir`(nearest directory with `tsconfig.json` or `package.json`). If it doesn't find tsserver starts walking up into directory structure and look for `node_modules` to check. If it also doesn't find it as last resort use your global installation.

You can also enable nvim lsp trace logs by `vim.lsp.set_log_level("trace")` and in `:LspInfo` you get paths where plugin try to find tsserver. You may confront them with your workspace. Below file shows how logs should look like:
https://github.com/pmizio/typescript-tools.nvim/blob/4f4f3874475ea08fbc6ed7a002495bdd24376932/lua/typescript-tools/tsserver_provider.lua

**Comment by lucasmarinb** [comment]
I see. As context, I'm working in a node project without typescript, and I was previously using `typescript.nvim` plugin which itself used the `typescript-language-server`. So, the nearest directory with a `package.json` was the same project, but it doesn't have anything related to typescript installed.

I may say that the behaviour I'm expecting is to be able to create a javascript (no typescript) project from scratch and to have lsp features enabled.

Thanks for your help!

**Comment by pmizio** [comment]
Ok, so for now global ts installation for you is best solution, I have plan to support maybe custom registry with ts versions and ts plugins via mason but I have not eta for it for now.

**Comment by lucasmarinb** [comment]
No problem. Is there any way to help or get involved with the development of this feature?

**Comment by pmizio** [comment]
@lucasmarinb  Ofc, If you want to help it would be awesome. You can start [here](https://github.com/pmizio/typescript-tools.nvim/blob/1b0af278f7415bc8fbb8128af99622dffcf5a9c2/lua/typescript-tools/tsserver_provider.lua#L106), this function check places where tsserver can be found. So we need new one for mason.
Some requirements, I don't want to mason become mandatory so, if mason isn't installed in config we skip its integration code. For now we can use tsserver installed inside `typescript-language-server`, but in readme should be mentioned to disable its lspconfig configuration.

**Comment by lucasmarinb** [comment]
Ok, I'll take a look.
