### ISSUE TITLE
Client exit on tsx file open

### ISSUE THREAD

**Issue by TisnKu** [pmizio/typescript-tools.nvim#61]
I opened a yarn workspace mono repo project that I work on daily and enter one of the tsx files, then the client crashes with following info.

Message:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/10512841/f6c662a0-fcc8-4584-9bd8-5de494606b51)

LspInfo:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/10512841/b8407336-9469-4bca-8330-ab3cd48b4716)

LspLog:
![image](https://github.com/pmizio/typescript-tools.nvim/assets/10512841/da86870c-14e9-4367-a5e6-22981bc20834)

**Comment by pmizio** [comment]
@TisnKu Is this possibly fixed by https://github.com/pmizio/typescript-tools.nvim/pull/67, can I close this?
