### ISSUE TITLE
Issue with enabling inlay hints

### ISSUE THREAD

**Issue by raphaelluethy** [pmizio/typescript-tools.nvim#63]
What I expect to happen:
I set up the plugin with the following commands:
```lua
require("typescript-tools").setup({
    settings = {
        -- spawn additional tsserver instance to calculate diagnostics on it
        separate_diagnostic_server = true,
        -- "change"|"insert_leave" determine when the client asks the server about diagnostic
        publish_diagnostic_on = "change",
        tsserver_file_preferences = {
            includeInlayParameterNameHints = "all",
            includeInlayEnumMemberValueHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayVariableTypeHints = true
        },
        tsserver_format_options = {
            allowIncompleteCompletions = false,
            allowRenameOfImportPath = false
        }
    }
})

```
and there should be inlay hints according to the docs. I also checked the source code to see if I have all inlay preferences enabled.

Instead I get the following:
<img width="581" alt="CleanShot 2023-06-22 at 22 54 13@2x" src="https://github.com/pmizio/typescript-tools.nvim/assets/55560043/2034144a-7492-4017-adf7-34beb7567711">
Also I would like to add, that the code actions work just fine.

Setup:
I use lsp-zero as a base for my lsp configuration.

Here is also the link for my current config: https://github.com/raphaelluethy/nvim

Do you have any idea what the issue could be?

**Comment by pmizio** [comment]
This enable server capability to support for inlay hints in  tsserver but client support is up to you - if you on stable neovim you need additional plugin to show inlay hints or in nightly you can use build in implementation.

**Comment by raphaelluethy** [comment]
ah okay, I missunderstood, thank you very much!

**Comment by barrett-ruth** [comment]
@pmizio neovim recently added support for inlay hints in neovim 0.10. However, I still don't seem to see any inlay hints showing up (despite having the README configuration copied letter for letter). Should these features work on the new neovim release (granted, it has only been a few days since)?

**Comment by pmizio** [comment]
@barrett-ruth Yes inlay hints from nightly work but you need in plugin config:
```lua
        tsserver_file_preferences = {
            includeInlayParameterNameHints = "all",
            includeInlayEnumMemberValueHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayVariableTypeHints = true
        },
```

For now I wont add docs for it because it isn't in stable anyway.

**Comment by raphaelluethy** [comment]
> @barrett-ruth Yes inlay hints from nightly work but you need in plugin config:
> 
> ```lua
>         tsserver_file_preferences = {
>             includeInlayParameterNameHints = "all",
>             includeInlayEnumMemberValueHints = true,
>             includeInlayFunctionLikeReturnTypeHints = true,
>             includeInlayFunctionParameterTypeHints = true,
>             includeInlayPropertyDeclarationTypeHints = true,
>             includeInlayVariableTypeHints = true
>         },
> ```
> 
> For now I wont add docs for it because it isn't in stable anyway.

This is how I got it to work for now 👍

**Comment by marcelarie** [comment]
This still does not work for me.

**Comment by Lewenhaupt** [comment]
@pmizio I'm able to get inline hints to work when I use lspconfig directly with tsserver but not when I use this plugin. Any guidance on what to do?

**Comment by devsunb** [comment]
To enable inlay hints, `vim.lsp.inlay_hint.enable(true)` should exist within the `on_attach` function.

My lazy.nvim configuration:

```lua
{
  'pmizio/typescript-tools.nvim',
  dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
  opts = {
    expose_as_code_action = 'all',
    settings = {
      tsserver_file_preferences = {
        includeInlayParameterNameHints = 'literals',
        includeInlayParameterNameHintsWhenArgumentMatchesName = false,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayVariableTypeHints = false,
        includeInlayVariableTypeHintsWhenTypeMatchesName = false,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayFunctionLikeReturnTypeHints = false,
        includeInlayEnumMemberValueHints = true,
      },
    },
    on_attach = function(client, bufnr)
      -- stylua: ignore
      if client.server_capabilities.inlayHintProvider then vim.lsp.inlay_hint.enable(true) end
      -- stylua: ignore
      local function map(mode, lhs, rhs, desc) vim.keymap.set(mode, lhs, rhs, { desc = desc, buffer = bufnr }) end
      map('n', '<Leader>ci', '<Cmd>TSToolsAddMissingImports<CR>', 'Add Missing Imports')
      map('n', '<Leader>co', '<Cmd>TSToolsOrganizeImports<CR>', 'Organize Imports')
      map('n', '<Leader>cR', '<Cmd>TSToolsFileReferences<CR>', 'File References')
    end,
  },
}
```
