### ISSUE TITLE
Warning: Client with id 4 not attached to buffer 18 (recently closed buffer)

### ISSUE THREAD

**Issue by ecosse3** [pmizio/typescript-tools.nvim#70]
Hi,

I have weird warning message each time I go to some buffers via LSP (definition) and I quit this buffer I got warning that **"Client with id 4 (`typescript-tools`) not attached to buffer 18 (`just closed buffed`)"**

I've checked and I have same error with `separate_diagnostic_server` enabled/disabled in plugin opts.

Demo:

https://github.com/pmizio/typescript-tools.nvim/assets/17691791/59183323-92ba-46fe-b28a-ea8096dc7b70

I've found some log in `:LspLog` but idk if it's related.

```lua
[WARN][2023-06-23 19:33:17] .../lua/vim/lsp.lua:1810	"buf_attach_client called on unloaded buffer (id: 73): "
[WARN][2023-06-23 19:33:17] .../lua/vim/lsp.lua:1810	"buf_attach_client called on unloaded buffer (id: 73): "
```

I am using `echasnovski/mini.bufremove` plugin for removing buffers but same happens with native nvim `:bdelete` command.

**Comment by pmizio** [comment]
@ecosse3 I'm looked into it and it look like it isn't on our side, this message is from: https://github.com/neovim/neovim/blame/4dc86477b674d056b137a3afafd8824f7b7717ec/runtime/lua/vim/lsp/semantic_tokens.lua#L593
It mean you was fast enough to close buffer before it was attached to sematic token engine.
If I was able reproduce this for eg. lua also.

**Comment by ecosse3** [comment]
Actually, I can be in the buffer even 30 seconds or more after _going to definition_, and when I close it I still see the warning message. Anyway, adding the

```lua
client.server_capabilities.semanticTokensProvider = nil
```

fixed the issue. Is there a way to fix this while keeping semantic tokens? I like to use semantic highlighting with treesitter.

**Comment by pmizio** [comment]
Probably, on my side I get this warning only if I'm really quick in closing goto definition buffer. So I cannot debug and reporoduce this. It may be some other plugin or some setting idk, if you provide me more information I try to fix that.

**Comment by pmizio** [comment]
@ecosse3 is your config somehow portable, I can try to use it and maybe on your stuff I will find something?

**Comment by ecosse3** [comment]
I am a bit less active this weekend. Here is my nvim config: https://github.com/ecosse3/nvim/tree/typescript-tools

You can just clone it and run. You may need to install `ts`/`tsx` treesitter parsers by `:TSInstall`. I will try to check where can be the problem too. Thank you!

**Comment by pmizio** [comment]
@ecosse3 Ok, today I have a bit time to look into that and it's something "no-yes" with lazyloading of plugin. When I disabled ["lazyload everything by default"](https://github.com/ecosse3/nvim/blob/fc18e3b9dc3726b0618a0beeddc7faa32d660a4c/lua/config/lazy.lua#L15C1) in your config notification stop showing up. For now I don't know why but its some clue.

**Comment by ecosse3** [comment]
@pmizio Thank you. I was disabling each plugin by each and then each LSP server by each. I realized that removing `eslint` LSP setup solved this issue. I am still trying to figure out why `eslint` LSP server is causing this, but looks like this issue is not related to `typescript-tools`. Somehow `eslint` LSP causes this issue. Thank you for help!

**Comment by pmizio** [comment]
I use eslint lsp daily, but I barely lazy load anything and for me it's working just fine. So, combo of eslint lsp + this plugin + lazy loading breaks something. I look into it, even if it isn't our issue its worth to know why.

**Comment by ecosse3** [comment]
@pmizio Somehow this problem is gone. I guess it could be related to `eslint` LSP itself. I cannot reproduce it anymore.

**Comment by pmizio** [comment]
Oh nice thanks for letting me know!
