### ISSUE TITLE
Workspace symbols includes results from node_modules

### ISSUE THREAD

**Issue by MariaSolOs** [pmizio/typescript-tools.nvim#72]
When using Telescope's builtin of `lsp_dynamic_workspace_symbols`, results from `node_modules` are included. This quite affects performance.

<img width="1209" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/62502207/f897dd50-2e3b-4c6b-8679-58f4bd9da36b">

**Comment by pmizio** [comment]
I looked into that and it isn't on our side alt least not entirely. We make almost the same call as vscode do for workspace symbols only one difference is vscode add limit of 256. But performance of VSCode nad nvim regarding workspace symbols is comparable.
BUT! I looked into [code](https://github.com/typescript-language-server/typescript-language-server/blob/9f3e578792161095aab0eccb4c3e394dd9a4e697/src/lsp-server.ts#L1170) of `typescript-language-server` and it look like for this request it can work as document symbol. Please try `:Telescope lsp_document_symbols` instead. It PROBABLY work like you expect.

**Comment by pmizio** [comment]
Ignore previous message I look deeper and [this](https://github.com/pmizio/typescript-tools.nvim/pull/74) pr should fix problem.

**Comment by MariaSolOs** [comment]
> Ignore previous message I look deeper and [this](https://github.com/pmizio/typescript-tools.nvim/pull/74) pr should fix problem.

I confirm that the PR fixes it :)
