### ISSUE TITLE
Incorrect inferred return type (?)

### ISSUE THREAD

**Issue by MariaSolOs** [pmizio/typescript-tools.nvim#75]
Notice how inlay hints correctly show how the inferred return type is `string`, which contradicts the diagnostic.

This doesn't happen in VS Code.

<img width="1512" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/62502207/388b95d8-3dbf-4223-9ec4-005500084bc8">

If you want to investigate @pmizio, the repro is opening [this file](https://github.com/microsoft/TypeScript/blob/aec9e237815cacb00675f8ef925666e063412e21/src/compiler/emitter.ts).

**Comment by pmizio** [comment]
I see that and I will look into it deeper for now I was able to determinate potential elephant in the room - semanticTokens, as workaround if you don't care too much about semanticTokens you can disable them and sync problem disappear. Call this:
`client.server_capabilities.semanticTokensProvider = nil`  in your on_attach function.

Or maybe you have some insider info which can be helpful in fixing this? For now I will try to "reverse engineer" this from vscode code and tsserver logs, but it may take some time sorry :(

**Comment by KostkaBrukowa** [comment]
Just out of curiosity, why semantic tokens impact diagnostics?

**Comment by MariaSolOs** [comment]
@pmizio Thank you for the amazing investigation! I thought it was caused by the separate diagnostic server being out of sync with the syntax one (since I found it really weird how the same client would infer different types for different LSP methods), but you're the pro here :)

**Comment by pmizio** [comment]
@KostkaBrukowa Honestly no idea, I checked requests one by one and this one fixed problem. But both are sementic component and runned on same server so maybe this is a link.

**Comment by MariaSolOs** [comment]
@pmizio amazing. Also sorry for stress-testing your plugin with literally one of the most complicated repos out there 😸

**Comment by pmizio** [comment]
It's ok, if I didn't want it, the repowould still be private 😉

**Comment by pmizio** [comment]
@MariaSolOs pr https://github.com/pmizio/typescript-tools.nvim/pull/79 contain change - now for this large files semantic tokens are skipped. Can you verify this on free time?

**Comment by MariaSolOs** [comment]
@pmizio I just tried your branch in the TypeScript repo, and it works :)

**Comment by MariaSolOs** [comment]
While testing though, I noticed that inlay hints are only displayed after entering insert mode. Not sure if this is intended.

**Comment by pmizio** [comment]
@MariaSolOs True, I only tested them only by enabling them manually using cmdline. So I just cannot notice this. But it should be fixed now in mentioned pr.

**Comment by pmizio** [comment]
@MariaSolOs

**Comment by MariaSolOs** [comment]
@pmizio I just tried the latest main and it works like a charm!
