### ISSUE TITLE
Feature request: Ignored diagnostics by code

### ISSUE THREAD

**Issue by dwoznicki** [pmizio/typescript-tools.nvim#80]
The typescript-language-server project has a `diagnostics.ignoredCodes` setting that allows us to ignore certain diagnostics by code. Specifically, I find 80006 "This may be converted to an async function." to be particularly annoying. It would be nice to have a similar `ignoredCodes` option to turn off unwanted diagnostics messages.

**Comment by MariaSolOs** [comment]
@pmizio may I take a look at this :) ?

**Comment by MariaSolOs** [comment]
> @pmizio may I take a look at this :) ?

Not trying to lick the cookie here, just making sure you're not already working on it hehe.

**Comment by pmizio** [comment]
Yes, I look into it tomorrow, this and next weekend I will be a little bit less active because vacation time in my country ;)

**Comment by pmizio** [comment]
@MariaSolOs My idea how to do that isn't in diagnostic code itself, but we can use nvim feature to override response handler a bit of pseudo code:
```lua
local api = require("typescript-tools.api")

require("typescript-tools").setup {
  on_attach = ...,
  handlers = {
    ["textDocument/publishDiagnostics"] = api.utils.filter_diagnostic_codes({1, 2, 3}),
  },
}

**Comment by MariaSolOs** [comment]
@pmizio sounds good! So do you want users to filter the diagnostics via settings using such snippet, or do you want them to only provide the codes and leave the filters to the plugin?

**Comment by pmizio** [comment]
1st one I don't want to overcomplicate code of diagnostics which is complicated now. Beside adding one utility function is easier to understand, test and maintain.

**Comment by pmizio** [comment]
@dwoznicki it's now on master and instruction is in README
