### ISSUE TITLE
Cannot disable formatting capabilities

### ISSUE THREAD

**Issue by TisnKu** [pmizio/typescript-tools.nvim#81]
Tsserver format conflicts with prettier, so I need to disable it. However previous way to disable it does not work. I can only modify the capabilities.lua file in this repo to make it work.

My configuration:
```
  use({
    "pmizio/typescript-tools.nvim",
    requires = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    config = function()
      require("typescript-tools").setup {
        on_attach = function(client)
          client.server_capabilities.documentFormattingProvider = false
          client.server_capabilities.documentRangeFormattingProvider = false
        end,
        settings = {
          tsserver_max_memory = 8092,
          separate_diagnostic_server = false,
        }
      }
    end,
  })

```

**Comment by pmizio** [comment]
Huh, thats weird i literally copied disabling capabilities from your `on_attach` and this disabling requests for me. Maybe this is neovim version related, can you provide me what version you using @TisnKu

**Comment by TisnKu** [comment]
@pmizio I tested again and cannot reproduce. Close the issue.

My neovim version: NVIM v0.10.0-dev-46+ge23c6ebed
