### ISSUE TITLE
Can you support renaming files?

### ISSUE THREAD

**Issue by aaronmcadam** [pmizio/typescript-tools.nvim#94]
First of all, fantastic work on this plugin; it's brilliant! :tada:

One feature I'm missing from https://github.com/jose-elias-alvarez/typescript.nvim is the ability to rename files. In `typescript.nvim`, the command is `:TypescriptRenameFile`.

Is this on your backlog already? Thanks!

**Comment by pmizio** [comment]
For now it is only supported using [this plugin](https://github.com/antosha417/nvim-lsp-file-operations) which integrates `nvim-tree` with lsp to do additional changes after rename. But command can be added.

**Comment by KostkaBrukowa** [comment]
I would also recommend using `nvim-lsp-file-operations` because it also allows you to rename whole directories (Rename file I guess does not have this ability)

**Comment by Cretezy** [comment]
Is there any support for neo-tree with any plugins? This feature is the only one I still have to reach for other editors in my workflow.

**Comment by pmizio** [comment]
I don't know about any, but you can post issue to mentioned plugin for support to `neo-tree`. From our side we add support for basic vim command to do this, but I don't have eta for it.

**Comment by KostkaBrukowa** [comment]
@Cretezy 4 days ago there was an update to `nvim-lsp-file-operations` to support neo-tree. You can update the plugin and check if it works with `typescript-tools`

**Comment by aaronmcadam** [comment]
I don't use a file tree plugin. Are there any other options for users like me? 😄

**Comment by pmizio** [comment]
As far as I know sadly no. We plan to expose this as vim commands also, but I don't have any eta for this.
It is relatively simple thing so if you in rush contributions are always welcome.

**Comment by pmizio** [comment]
Command is on master introduced in this PR: https://github.com/pmizio/typescript-tools.nvim/pull/170 enjoy!
