### ISSUE TITLE
Running TSTools command synchronously

### ISSUE THREAD

**Issue by NickP-real** [pmizio/typescript-tools.nvim#95]
let's say I want to do all tstools commands before the format command executes.
But the problem is these tstools commands aren't yet finished, the format has executed.
any way to do this kind of thing?

```lua
function on_attach() then
  local function before_format()
    vim.cmd.TSToolsRemoveUnusedImports()
    vim.cmd.TSToolsAddMissingImports()
    vim.cmd.TSToolsSortImports()
    vim.cmd.TSToolsOrganizeImports()
    vim.cmd.TSToolsFixAll()
  end
  utils.no_format_on_attach(client, bufnr)
  vim.api.nvim_del_augroup_by_name(utils.null_ls_format_group_name(bufnr))
  utils.format(client, bufnr, function(lsp_client)
    return lsp_client.name == "null-ls"
  end, before_format)
end

-- this is utils.format
M.format = function(client, bufnr, filter, func)
  vim.api.nvim_create_autocmd("BufWritePre", {
    desc = client.name,
    buffer = bufnr,
    callback = function()
      if M.auto_format_enable then
        if func then
          func()
        end
        vim.lsp.buf.format({ bufnr = bufnr, filter = filter })
      end
    end,
    group = M.format_group(client, bufnr),
  })
end

```

**Comment by KostkaBrukowa** [comment]
Ye right not the commands are async, but the only thing that makes them async [is this line](https://github.com/pmizio/typescript-tools.nvim/blob/master/lua/typescript-tools/api.lua#L28). There is also the alternative method `request_sync` that would meet your expectations. I you have the time to make the change any PR is welcome

**Comment by NickP-real** [comment]
for now, I have errors around vim.lsp.buf_request_sync

the buf_request is doing fine, but when I try buf_request_sync, the file hasn't changed plus got a table containing the error and result.

It's only two functions left now, organize import and go_to_source_definition, the rest that uses send_batch_code_action is ok.

**Comment by pmizio** [comment]
@NickP-real  ok, so looked into it and it works as expected - this erros are from other attached lsps which don't support our custom method. They are safe to ignore. Notice all responses including error ones are in table indexed with numbers, this numbers are ids of attached lsps. So to fix this you need to find typescript-tools id get correct response from returned value and pass it handler.
