### ISSUE TITLE
Weird lsp completion menu order

### ISSUE THREAD

**Issue by ribru17** [pmizio/typescript-tools.nvim#98]
Hi and thanks for the awesome plugin. One thing I noticed is that the completion menu (at least with cmp) is giving weird results compared to the regular `tsserver`, e.g. it prioritizes `[Symbol]` when accessing properties of an array.

### With just `tsserver`:

![tstoolsreg](https://github.com/pmizio/typescript-tools.nvim/assets/55766287/c1526120-4207-42e6-be62-1ea1c30e66e7)

### With  `typescript-tools.nvim`:

![tstoolsbug](https://github.com/pmizio/typescript-tools.nvim/assets/55766287/7b1c7d8d-6176-4b43-bd3d-13f4c1ee6c11)

Not the biggest deal but a bit annoying when I am quickly typing `l` and hit tab and get the `Symbol` property instead of `length`.
Hopefully someone can point me in the right direction or fix this if this is a bug. Thanks!

**Comment by pmizio** [comment]
Problem probably exists somewhere in (this file)[https://github.com/pmizio/typescript-tools.nvim/blob/master/lua/typescript-tools/protocol/text_document/completion/init.lua] probably deal is with sorting. We probably don't set some key property for cmp to correctly sort entries. To fix this we need to look into cmp code also.

**Comment by pmizio** [comment]
One other question do you have some special cmp configuration regarding sorting or you use defaults?

**Comment by ribru17** [comment]
Thanks, I'll take a look there. And no everything sorting is default, only thing I changed is the priority of the different sources (making luasnip higher priority) but since these are all from the same source I don't think it should matter.

**Comment by KostkaBrukowa** [comment]
Suprisingly VSCode completion is the same 
<img width="529" alt="image" src="https://github.com/pmizio/typescript-tools.nvim/assets/35625949/0e45cb89-094c-4773-a065-f3f63af8cc0f">

**Comment by KostkaBrukowa** [comment]
https://github.com/typescript-language-server/typescript-language-server/blob/983a6923114c39d638e0c7d419ae16e8bca8985c/src/completion.ts#L103
So this is the difference.
In TLS they always add a `textEdit` to the completion entry and our plugin does not. And for some reason `cmp` gives a better score for entries with `textEdit` than to those without - resulting in Symbol being on the top
